
package com.ccic.salesapp.noncar.outService.esb.quoteprice.intf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T12:48:05.979+08:00
 * Generated source version: 2.7.0
 * 
 */
public final class QuotePrice_QuotePriceEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ccic.com/lifePolicy/quotePrice/intf", "QuotePriceService");

    private QuotePrice_QuotePriceEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QuotePriceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QuotePriceService ss = new QuotePriceService(wsdlURL, SERVICE_NAME);
        QuotePrice port = ss.getQuotePriceEndpoint();  
        
        {
        System.out.println("Invoking quotePrice...");
        com.ccic.salesapp.noncar.outService.esb.quoteprice.bean.QuotePriceRequest _quotePrice_quotePriceRequest = null;
        com.ccic.salesapp.noncar.outService.esb.quoteprice.bean.QuotePriceResponse _quotePrice__return = port.quotePrice(_quotePrice_quotePriceRequest);
        System.out.println("quotePrice.result=" + _quotePrice__return);


        }

        System.exit(0);
    }

}
