package com.ccic.salesapp.noncar.outService.esb.quoteprice.intf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T12:48:06.047+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "QuotePriceService", 
                  wsdlLocation = "QuotePriceService.wsdl",
                  targetNamespace = "http://service.ccic.com/lifePolicy/quotePrice/intf") 
public class QuotePriceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/lifePolicy/quotePrice/intf", "QuotePriceService");
    public final static QName QuotePriceEndpoint = new QName("http://service.ccic.com/lifePolicy/quotePrice/intf", "QuotePriceEndpoint");
    static {
        URL url = QuotePriceService.class.getResource("QuotePriceService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(QuotePriceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "QuotePriceService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public QuotePriceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QuotePriceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuotePriceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public QuotePriceService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public QuotePriceService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public QuotePriceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns QuotePrice
     */
    @WebEndpoint(name = "QuotePriceEndpoint")
    public QuotePrice getQuotePriceEndpoint() {
        return super.getPort(QuotePriceEndpoint, QuotePrice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuotePrice
     */
    @WebEndpoint(name = "QuotePriceEndpoint")
    public QuotePrice getQuotePriceEndpoint(WebServiceFeature... features) {
        return super.getPort(QuotePriceEndpoint, QuotePrice.class, features);
    }

}
