package com.ccic.salesapp.noncar.outService.esb.quoteprice.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T12:48:06.040+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/lifePolicy/quotePrice/intf", name = "QuotePrice")
@XmlSeeAlso({com.ccic.salesapp.noncar.outService.esb.quoteprice.bean.ObjectFactory.class, com.ccic.salesapp.noncar.outService.esb.quoteprice.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QuotePrice {

    @WebResult(name = "QuotePriceResponse", targetNamespace = "http://service.ccic.com/lifePolicy/quotePrice/bean", partName = "QuotePriceResponse")
    @WebMethod(action = "/lifePolicy/quotoPrice")
    public com.ccic.salesapp.noncar.outService.esb.quoteprice.bean.QuotePriceResponse quotePrice(
        @WebParam(partName = "QuotePriceRequest", name = "QuotePriceRequest", targetNamespace = "http://service.ccic.com/lifePolicy/quotePrice/bean")
        com.ccic.salesapp.noncar.outService.esb.quoteprice.bean.QuotePriceRequest quotePriceRequest
    );
}
