
package com.ccic.salesapp.noncar.outService.esb.shorturl.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ccic.salesapp.noncar.outService.esb.shorturl.bean.ObjectFactory;
import com.ccic.salesapp.noncar.outService.esb.shorturl.bean.ShortUrlRequest;
import com.ccic.salesapp.noncar.outService.esb.shorturl.bean.ShortUrlResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShortUrlPort", targetNamespace = "http://service.ccic.com/netMarketing/shortUrl/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShortUrlPort {


    /**
     * 
     * @param shortUrlRequest
     * @return
     *     returns com.salesapp.webservice.ShortUrlResponse
     */
    @WebMethod(operationName = "ShortUrl", action = "/netMarketing/shortUrl")
    @WebResult(name = "ShortUrlResponse", targetNamespace = "http://service.ccic.com/netMarketing/shortUrl/bean", partName = "ShortUrlResponse")
    public ShortUrlResponse shortUrl(
        @WebParam(name = "ShortUrlRequest", targetNamespace = "http://service.ccic.com/netMarketing/shortUrl/bean", partName = "ShortUrlRequest")
        ShortUrlRequest shortUrlRequest);

}
