
package com.ccic.salesapp.noncar.outService.esb.shorturl.intf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShortUrlService", targetNamespace = "http://service.ccic.com/netMarketing/shortUrl/intf", wsdlLocation = "file:/D:/src/ShortUrlService.wsdl")
public class ShortUrlService
    extends Service
{

    private final static URL SHORTURLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHORTURLSERVICE_EXCEPTION;
    private final static QName SHORTURLSERVICE_QNAME = new QName("http://service.ccic.com/netMarketing/shortUrl/intf", "ShortUrlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/src/ShortUrlService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHORTURLSERVICE_WSDL_LOCATION = url;
        SHORTURLSERVICE_EXCEPTION = e;
    }

    public ShortUrlService() {
        super(__getWsdlLocation(), SHORTURLSERVICE_QNAME);
    }

    public ShortUrlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHORTURLSERVICE_QNAME, features);
    }

    public ShortUrlService(URL wsdlLocation) {
        super(wsdlLocation, SHORTURLSERVICE_QNAME);
    }

    public ShortUrlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHORTURLSERVICE_QNAME, features);
    }

    public ShortUrlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShortUrlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShortUrlPort
     */
    @WebEndpoint(name = "ShortUrlPort")
    public ShortUrlPort getShortUrlPort() {
        return super.getPort(new QName("http://service.ccic.com/netMarketing/shortUrl/intf", "ShortUrlPort"), ShortUrlPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShortUrlPort
     */
    @WebEndpoint(name = "ShortUrlPort")
    public ShortUrlPort getShortUrlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/netMarketing/shortUrl/intf", "ShortUrlPort"), ShortUrlPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHORTURLSERVICE_EXCEPTION!= null) {
            throw SHORTURLSERVICE_EXCEPTION;
        }
        return SHORTURLSERVICE_WSDL_LOCATION;
    }

}
