package com.ccic.salesapp.noncar.outService.esb.withholdorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-12-13T15:38:50.989+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "WithholdOrderService", 
                  wsdlLocation = "file:/E:/CXF/WithholdOrderService.wsdl",
                  targetNamespace = "http://service.ccic.com/pss/withholdOrder/intf") 
public class WithholdOrderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/pss/withholdOrder/intf", "WithholdOrderService");
    public final static QName WithholdOrderEndpoint = new QName("http://service.ccic.com/pss/withholdOrder/intf", "WithholdOrderEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/CXF/WithholdOrderService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WithholdOrderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/CXF/WithholdOrderService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WithholdOrderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WithholdOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WithholdOrderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WithholdOrderPort
     */
    @WebEndpoint(name = "WithholdOrderEndpoint")
    public WithholdOrderPort getWithholdOrderEndpoint() {
        return super.getPort(WithholdOrderEndpoint, WithholdOrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WithholdOrderPort
     */
    @WebEndpoint(name = "WithholdOrderEndpoint")
    public WithholdOrderPort getWithholdOrderEndpoint(WebServiceFeature... features) {
        return super.getPort(WithholdOrderEndpoint, WithholdOrderPort.class, features);
    }

}
