package com.ccic.salesapp.noncar.outService.esb.withholdorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-12-13T15:38:50.908+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/pss/withholdOrder/intf", name = "WithholdOrderPort")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WithholdOrderPort {

    @WebResult(name = "WithholdOrderResponse", targetNamespace = "http://service.ccic.com/pss/withholdOrder/bean", partName = "WithholdOrderResponse")
    @WebMethod(action = "/pss/withholdOrder")
    public WithholdOrderResponse withholdOrder(
        @WebParam(partName = "WithholdOrderRequest", name = "WithholdOrderRequest", targetNamespace = "http://service.ccic.com/pss/withholdOrder/bean")
        WithholdOrderRequest withholdOrderRequest
    );
}
