package com.ccic.salesapp.noncar.outService.esb.sms.intf;

import com.ccic.salesapp.noncar.outService.esb.sms.bean.SendSmsRequest;
import com.ccic.salesapp.noncar.outService.esb.sms.bean.SendSmsResponse;

import com.ccic.salessapp.common.outService.ws.common.bean.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSms", targetNamespace = "http://service.ccic.com/sms/sendSms/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSms {


    /**
     * 
     * @param sendSmsRequest
     * @return
     *     returns com.salesapp.webservice.SendSmsResponse
     */
    @WebMethod(action = "/sms/sendSms")
    @WebResult(name = "SendSmsResponse", targetNamespace = "http://service.ccic.com/sms/sendSms/bean", partName = "SendSmsResponse")
    public SendSmsResponse sendSms(
            @WebParam(name = "SendSmsRequest", targetNamespace = "http://service.ccic.com/sms/sendSms/bean", partName = "SendSmsRequest")
                    SendSmsRequest sendSmsRequest);

}

