package com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.intf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T11:39:11.341+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "ProposalLiabInsGenerateService", 
                  wsdlLocation = "ProposalLiabInsGenerateService.wsdl",
                  targetNamespace = "http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/intf") 
public class ProposalLiabInsGenerateService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/intf", "ProposalLiabInsGenerateService");
    public final static QName ProposalLiabInsGenerateEndpoint = new QName("http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/intf", "ProposalLiabInsGenerateEndpoint");
    static {
        URL url = ProposalLiabInsGenerateService.class.getResource("ProposalLiabInsGenerateService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ProposalLiabInsGenerateService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "ProposalLiabInsGenerateService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ProposalLiabInsGenerateService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProposalLiabInsGenerateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProposalLiabInsGenerateService() {
        super(WSDL_LOCATION, SERVICE);
    }
   
    /**
     *
     * @return
     *     returns ProposalLiabInsGeneratePort
     */
    @WebEndpoint(name = "ProposalLiabInsGenerateEndpoint")
    public ProposalLiabInsGeneratePort getProposalLiabInsGenerateEndpoint() {
        return super.getPort(ProposalLiabInsGenerateEndpoint, ProposalLiabInsGeneratePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProposalLiabInsGeneratePort
     */
    @WebEndpoint(name = "ProposalLiabInsGenerateEndpoint")
    public ProposalLiabInsGeneratePort getProposalLiabInsGenerateEndpoint(WebServiceFeature... features) {
        return super.getPort(ProposalLiabInsGenerateEndpoint, ProposalLiabInsGeneratePort.class, features);
    }

}
