
package com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.intf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T11:39:11.248+08:00
 * Generated source version: 2.7.0
 * 
 */
public final class ProposalLiabInsGeneratePort_ProposalLiabInsGenerateEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/intf", "ProposalLiabInsGenerateService");

    private ProposalLiabInsGeneratePort_ProposalLiabInsGenerateEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProposalLiabInsGenerateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProposalLiabInsGenerateService ss = new ProposalLiabInsGenerateService(wsdlURL, SERVICE_NAME);
        ProposalLiabInsGeneratePort port = ss.getProposalLiabInsGenerateEndpoint();  
        
        {
        System.out.println("Invoking proposalGenerate...");
        com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.bean.ProposalGenerateRequest _proposalGenerate_proposalGenerateRequest = null;
        com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.bean.ProposalGenerateResponse _proposalGenerate__return = port.proposalGenerate(_proposalGenerate_proposalGenerateRequest);
        System.out.println("proposalGenerate.result=" + _proposalGenerate__return);


        }

        System.exit(0);
    }

}
