package com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T11:39:11.332+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/intf", name = "ProposalLiabInsGeneratePort")
@XmlSeeAlso({com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.bean.ObjectFactory.class, com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProposalLiabInsGeneratePort {

    @WebResult(name = "ProposalGenerateResponse", targetNamespace = "http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/bean", partName = "ProposalGenerateResponse")
    @WebMethod(operationName = "ProposalGenerate", action = "/liabinsurance/proposalLiabInsGenerate")
    public com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.bean.ProposalGenerateResponse proposalGenerate(
        @WebParam(partName = "ProposalGenerateRequest", name = "ProposalGenerateRequest", targetNamespace = "http://service.ccic.com/liabinsurance/proposalLiabInsGenerate/bean")
        com.ccic.salesapp.noncar.outService.esb.proposalliabinsgenerate.bean.ProposalGenerateRequest proposalGenerateRequest
    );
}
