
package com.ccic.salesapp.noncar.outService.esb.entBaseInfoInquiry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.ccic.salesapp.noncar.outService.esb.entBaseInfoInquiry.bean.EntBaseInfoInquiryRequest;
import com.ccic.salesapp.noncar.outService.esb.entBaseInfoInquiry.bean.EntBaseInfoInquiryResponse;
import com.ccic.salesapp.noncar.outService.esb.entBaseInfoInquiry.intf.EntBaseInfoInquiry;
import com.ccic.salesapp.noncar.outService.esb.entBaseInfoInquiry.intf.EntBaseInfoInquiryService;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T15:42:49.370+08:00
 * Generated source version: 3.3.5
 *
 */
public final class EntBaseInfoInquiry_EntBaseInfoInquiryEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ccic.com/ecif/entbaseinfoinquiry/intf", "EntBaseInfoInquiryService");

    private EntBaseInfoInquiry_EntBaseInfoInquiryEndpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EntBaseInfoInquiryService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EntBaseInfoInquiryService ss = new EntBaseInfoInquiryService(wsdlURL, SERVICE_NAME);
        EntBaseInfoInquiry port = ss.getEntBaseInfoInquiryEndpoint();

        {
        System.out.println("Invoking process...");
        EntBaseInfoInquiryRequest _process_entBaseInfoInquiryRequest = null;
        EntBaseInfoInquiryResponse _process__return = port.process(_process_entBaseInfoInquiryRequest);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
