package com.ccic.salesapp.performance.outService.esb.sms.intf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-08-16T10:10:09.410+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "SendSmsService", 
                  wsdlLocation = "SendSmsService.wsdl",
                  targetNamespace = "http://service.ccic.com/sms/sendSms/intf") 
public class SendSmsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/sms/sendSms/intf", "SendSmsService");
    public final static QName SendSmsEndpoint = new QName("http://service.ccic.com/sms/sendSms/intf", "SendSmsEndpoint");
    static {
        URL url = SendSmsService.class.getResource("SendSmsService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SendSmsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SendSmsService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SendSmsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendSmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendSmsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public SendSmsService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public SendSmsService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public SendSmsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns SendSms
     */
    @WebEndpoint(name = "SendSmsEndpoint")
    public SendSms getSendSmsEndpoint() {
        return super.getPort(SendSmsEndpoint, SendSms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSms
     */
    @WebEndpoint(name = "SendSmsEndpoint")
    public SendSms getSendSmsEndpoint(WebServiceFeature... features) {
        return super.getPort(SendSmsEndpoint, SendSms.class, features);
    }

}
