package com.ccic.salesapp.noncar.outService.esb.userservice.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.ccic.salesapp.noncar.outService.esb.userservice.bean.UserAuthenticationRequest;
import com.ccic.salesapp.noncar.outService.esb.userservice.bean.UserAuthenticationResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserAuthenticationService", targetNamespace = "http://service.ccic.com/userservice/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserAuthenticationService {

	/**
	 * 
	 * @param userAuthenticationRequest
	 * @return returns
	 *         com.ccic.service.userservice.bean.UserAuthenticationResponse
	 */
	@WebMethod(action = "/userservice/authenticate")
	@WebResult(name = "UserAuthenticationResponse", targetNamespace = "http://service.ccic.com/userservice/bean", partName = "UserAuthenticationResponse")
	public UserAuthenticationResponse authenticate(
			@WebParam(name = "UserAuthenticationRequest", targetNamespace = "http://service.ccic.com/userservice/bean", partName = "UserAuthenticationRequest")
			UserAuthenticationRequest userAuthenticationRequest);

}
