
package com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.intf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T12:45:32.403+08:00
 * Generated source version: 2.7.0
 * 
 */
public final class ProposalGeneratePort_ProposalGenerateEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ccic.com/ecargo/proposalgenerate/intf", "ProposalGenerateService");

    private ProposalGeneratePort_ProposalGenerateEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProposalGenerateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProposalGenerateService ss = new ProposalGenerateService(wsdlURL, SERVICE_NAME);
        ProposalGeneratePort port = ss.getProposalGenerateEndpoint();  
        
        {
        System.out.println("Invoking proposalGenerate...");
        com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.bean.ProposalGenerateRequest _proposalGenerate_proposalGenerateRequest = null;
        com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.bean.ProposalGenerateResponse _proposalGenerate__return = port.proposalGenerate(_proposalGenerate_proposalGenerateRequest);
        System.out.println("proposalGenerate.result=" + _proposalGenerate__return);


        }

        System.exit(0);
    }

}
