package com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ccic.salessapp.common.outService.ws.common.bean.ObjectFactory;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-07-24T12:45:32.454+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/ecargo/proposalgenerate/intf", name = "ProposalGeneratePort")
@XmlSeeAlso({ObjectFactory.class, com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProposalGeneratePort {

    @WebResult(name = "ProposalGenerateResponse", targetNamespace = "http://service.ccic.com/ecargo/proposalgenerate/bean", partName = "ProposalGenerateResponse")
    @WebMethod(action = "/ecargo/proposalgenerate")
    public com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.bean.ProposalGenerateResponse proposalGenerate(
        @WebParam(partName = "ProposalGenerateRequest", name = "ProposalGenerateRequest", targetNamespace = "http://service.ccic.com/ecargo/proposalgenerate/bean")
        com.ccic.salesapp.noncar.outService.esb.ecargo.proposalgenerate.bean.ProposalGenerateRequest proposalGenerateRequest
    );
}
