package com.ccic.salesapp.noncar.outService.esb.h5imgquerydown.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ccic.salesapp.noncar.outService.esb.h5imgquerydown.bean.H5ImgQueryDownRequest;
import com.ccic.salesapp.noncar.outService.esb.h5imgquerydown.bean.H5ImgQueryDownResponse;
import com.ccic.salessapp.common.outService.ws.common.bean.ObjectFactory;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2020-03-17T15:21:30.967+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/h5img/h5imgQueryDown/intf", name = "H5imgQueryDownPort")
@XmlSeeAlso({com.ccic.salesapp.noncar.outService.esb.h5imgquerydown.bean.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface H5ImgQueryDownPort {

    @WebMethod(operationName = "H5imgQueryDown", action = "/h5img/h5imgQueryDown")
    @WebResult(name = "H5imgQueryDownResponse", targetNamespace = "http://service.ccic.com/h5img/h5imgQueryDown/bean", partName = "H5imgQueryDownResponse")
    public H5ImgQueryDownResponse h5ImgQueryDown(
        @WebParam(partName = "H5imgQueryDownRequest", name = "H5imgQueryDownRequest", targetNamespace = "http://service.ccic.com/h5img/h5imgQueryDown/bean")
        H5ImgQueryDownRequest h5ImgQueryDownRequest
    );
}
