package com.ccic.salesapp.noncar.outService.esb.h5imgquerydown.intf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2020-03-17T15:21:31.049+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "H5imgQueryDownService", 
                  wsdlLocation = "H5imgQueryDownService.wsdl",
                  targetNamespace = "http://service.ccic.com/h5img/h5imgQueryDown/intf") 
public class H5ImgQueryDownService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/h5img/h5imgQueryDown/intf", "H5imgQueryDownService");
    public final static QName H5ImgQueryDownPort = new QName("http://service.ccic.com/h5img/h5imgQueryDown/intf", "H5imgQueryDownPort");
    static {
        URL url = H5ImgQueryDownService.class.getResource("H5imgQueryDownService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(H5ImgQueryDownService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "H5imgQueryDownService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public H5ImgQueryDownService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public H5ImgQueryDownService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public H5ImgQueryDownService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns H5ImgQueryDownPort
     */
    @WebEndpoint(name = "H5imgQueryDownPort")
    public H5ImgQueryDownPort getH5ImgQueryDownPort() {
        return super.getPort(H5ImgQueryDownPort, H5ImgQueryDownPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns H5ImgQueryDownPort
     */
    @WebEndpoint(name = "H5imgQueryDownPort")
    public H5ImgQueryDownPort getH5ImgQueryDownPort(WebServiceFeature... features) {
        return super.getPort(H5ImgQueryDownPort, H5ImgQueryDownPort.class, features);
    }

}
