package com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.intf;

import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.bean.ObjectFactory;
import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.bean.PerBaseInfoInquiryRequest;
import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.bean.PerBaseInfoInquiryResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-02-27T16:59:11.740+08:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://service.ccic.com/ecif/perbaseinfoinquiry/intf", name = "PerBaseInfoInquiry")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PerBaseInfoInquiry {

    @WebMethod(action = "/ecif/perbaseinfoinquiry")
    @WebResult(name = "PerBaseInfoInquiryResponse", targetNamespace = "http://service.ccic.com/ecif/perbaseinfoinquiry/bean", partName = "PerBaseInfoInquiryResponse")
    public PerBaseInfoInquiryResponse process(
            @WebParam(partName = "PerBaseInfoInquiryRequest", name = "PerBaseInfoInquiryRequest", targetNamespace = "http://service.ccic.com/ecif/perbaseinfoinquiry/bean")
                    PerBaseInfoInquiryRequest perBaseInfoInquiryRequest
    );
}
