export const formInfo = {
  code: "1",
  data: {
    bizId: 1,
    formulaCode: "WTN2050024",
    strategyId: 2,
    planId: 50,
    planBatch: null,
    planElementGroup: [
      {
        id: 1,
        planId: 0,
        bizId: 0,
        sourceGroupId: 0,
        category: "policy",
        code: "applicant",
        name: "投保人信息",
        sort: 1,
        planElementList: [
          {
            id: 1,
            groupId: 0,
            sourceElementId: 1,
            code: "appliName",
            name: "投保人姓名",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 1,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript:
              '[{"click":"appliNameClick(code1,code2)"},{"blur":"appliNameBlur(code1,code2)"}]',
            validateType: "name",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 2,
            groupId: 0,
            sourceElementId: 2,
            code: "appliIdentifyType",
            name: "证件类型",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 2,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [
              {
                id: 1,
                elementId: 0,
                sourceOptionId: 0,
                value: "01",
                label: "身份证",
                selected: 1,
                sort: 1,
                children: []
              },
              {
                id: 2,
                elementId: 0,
                sourceOptionId: 0,
                value: "03",
                label: "护照",
                selected: 0,
                sort: 2,
                children: []
              },
              {
                id: 3,
                elementId: 0,
                sourceOptionId: 0,
                value: "28",
                label: "港澳台居民居住证",
                selected: 0,
                sort: 3,
                children: []
              }
            ],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "select",
            eventScript: "0",
            validateType: "idType",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 3,
            groupId: 0,
            sourceElementId: 3,
            code: "appliIdentifyNo",
            name: "证件号码",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 3,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "idNum",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 4,
            groupId: 0,
            sourceElementId: 4,
            code: "appliBirthDate",
            name: "出生日期",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 4,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "Date",
            controlType: "DatePicker",
            eventScript: "0",
            validateType: "birthday",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 5,
            groupId: 0,
            sourceElementId: 5,
            code: "appliMobile",
            name: "手机号",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 5,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "phone",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 6,
            groupId: 0,
            sourceElementId: 6,
            code: "appliEmail",
            name: "邮箱",
            requireInput: 0,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 6,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "email",
            placeholder: "0",
            linkElementCode: []
          }
        ]
      },
      {
        id: 2,
        planId: 0,
        bizId: 0,
        sourceGroupId: 0,
        category: "policy",
        code: "insured",
        name: "被保人信息",
        sort: 2,
        planElementList: [
          {
            id: 7,
            groupId: 0,
            sourceElementId: 7,
            code: "insuredAppliRelation",
            name: "与投保人关系",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 1,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [
              {
                id: 4,
                elementId: 0,
                sourceOptionId: 0,
                value: "01",
                label: "本人",
                selected: 0,
                sort: 1,
                children: []
              },
              {
                id: 5,
                elementId: 0,
                sourceOptionId: 0,
                value: "50",
                label: "父母",
                selected: 1,
                sort: 2,
                children: []
              },
              {
                id: 6,
                elementId: 0,
                sourceOptionId: 0,
                value: "10",
                label: "配偶",
                selected: 0,
                sort: 3,
                children: []
              },
              {
                id: 7,
                elementId: 0,
                sourceOptionId: 0,
                value: "40",
                label: "子女",
                selected: 0,
                sort: 4,
                children: []
              }
            ],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "select",
            eventScript: "0",
            validateType: "relation",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 8,
            groupId: 0,
            sourceElementId: 8,
            code: "insuredName",
            name: "被保人姓名",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 2,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "name",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 9,
            groupId: 0,
            sourceElementId: 9,
            code: "insuredIdentifyType",
            name: "证件类型",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 3,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "insuredIdentifyType",
            placeholder: "1",
            linkElementCode: []
          },
          {
            id: 10,
            groupId: 0,
            sourceElementId: 10,
            code: "insuredIdentifyNo",
            name: "证件号码",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 4,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "name",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 11,
            groupId: 0,
            sourceElementId: 11,
            code: "insuredBirthDate",
            name: "出生日期",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 5,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "name",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 12,
            groupId: 0,
            sourceElementId: 12,
            code: "insuredMobile",
            name: "手机号",
            requireInput: 0,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 6,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "input",
            eventScript: "0",
            validateType: "name",
            placeholder: "0",
            linkElementCode: []
          },
          {
            id: 13,
            groupId: 0,
            sourceElementId: 13,
            code: "insuredSheBaoType",
            name: "社保类型",
            requireInput: 1,
            defaultValue: "0",
            arrayIndex: 0,
            submitName: "",
            sort: 7,
            trialFlag: 0,
            trialSort: 0,
            planElementOptionList: [
              {
                id: 36,
                elementId: 0,
                sourceOptionId: 0,
                value: "11",
                label: "身份证",
                selected: 0,
                sort: 0,
                children: []
              },
              {
                id: 37,
                elementId: 0,
                sourceOptionId: 0,
                value: "12",
                label: "军官证",
                selected: 0,
                sort: 0,
                children: []
              },
              {
                id: 40,
                elementId: 0,
                sourceOptionId: 0,
                value: "13",
                label: "居住证",
                selected: 0,
                sort: 0,
                children: []
              },
              {
                id: 11,
                elementId: 0,
                sourceOptionId: 0,
                value: "1",
                label: "城镇职工基本医疗保险",
                selected: 0,
                sort: 1,
                children: []
              },
              {
                id: 12,
                elementId: 0,
                sourceOptionId: 0,
                value: "8",
                label: "城乡居民基本医疗保险",
                selected: 0,
                sort: 2,
                children: []
              },
              {
                id: 13,
                elementId: 0,
                sourceOptionId: 0,
                value: "2",
                label: "城镇居民基本医疗保险",
                selected: 0,
                sort: 3,
                children: []
              },
              {
                id: 14,
                elementId: 0,
                sourceOptionId: 0,
                value: "3",
                label: "新农合医疗保险",
                selected: 0,
                sort: 4,
                children: []
              },
              {
                id: 15,
                elementId: 0,
                sourceOptionId: 0,
                value: "7",
                label: "公费医疗",
                selected: 0,
                sort: 5,
                children: []
              },
              {
                id: 16,
                elementId: 0,
                sourceOptionId: 0,
                value: "4",
                label: "民政优抚医疗保险",
                selected: 0,
                sort: 6,
                children: []
              },
              {
                id: 17,
                elementId: 0,
                sourceOptionId: 0,
                value: "6",
                label: "其他",
                selected: 0,
                sort: 7,
                children: []
              }
            ],
            minLength: 0,
            maxLength: 100,
            minValue: 0,
            maxValue: 100,
            elementType: "String",
            controlType: "select",
            eventScript: "0",
            validateType: "insuredSheBaoType",
            placeholder: "0",
            linkElementCode: []
          }
        ]
      }
    ]
  },
  msg: "SUCCESS"
};
