package com.ccic.salesapp.noncar.dto.response;
import java.math.BigDecimal;
import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.CREATE_DATE
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.ORDER_NO
	 * @mbggenerated
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.IDENTITY_CODE
	 * @mbggenerated
	 */
	private String identityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.PAY_TYPE
	 * @mbggenerated
	 */
	private String payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.PAY_TYPE_NO
	 * @mbggenerated
	 */
	private String payTypeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_ORDER.PAY_AMOUNT
	 * @mbggenerated
	 */
	private BigDecimal payAmount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.ID
	 * @return  the value of B2BBUSI.T_ORDER.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.ID
	 * @param id  the value for B2BBUSI.T_ORDER.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.CREATE_DATE
	 * @return  the value of B2BBUSI.T_ORDER.CREATE_DATE
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.CREATE_DATE
	 * @param createDate  the value for B2BBUSI.T_ORDER.CREATE_DATE
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.ORDER_NO
	 * @return  the value of B2BBUSI.T_ORDER.ORDER_NO
	 * @mbggenerated
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.ORDER_NO
	 * @param orderNo  the value for B2BBUSI.T_ORDER.ORDER_NO
	 * @mbggenerated
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.IDENTITY_CODE
	 * @return  the value of B2BBUSI.T_ORDER.IDENTITY_CODE
	 * @mbggenerated
	 */
	public String getIdentityCode() {
		return identityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.IDENTITY_CODE
	 * @param identityCode  the value for B2BBUSI.T_ORDER.IDENTITY_CODE
	 * @mbggenerated
	 */
	public void setIdentityCode(String identityCode) {
		this.identityCode = identityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.PAY_TYPE
	 * @return  the value of B2BBUSI.T_ORDER.PAY_TYPE
	 * @mbggenerated
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.PAY_TYPE
	 * @param payType  the value for B2BBUSI.T_ORDER.PAY_TYPE
	 * @mbggenerated
	 */
	public void setPayType(String payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.PAY_TYPE_NO
	 * @return  the value of B2BBUSI.T_ORDER.PAY_TYPE_NO
	 * @mbggenerated
	 */
	public String getPayTypeNo() {
		return payTypeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.PAY_TYPE_NO
	 * @param payTypeNo  the value for B2BBUSI.T_ORDER.PAY_TYPE_NO
	 * @mbggenerated
	 */
	public void setPayTypeNo(String payTypeNo) {
		this.payTypeNo = payTypeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_ORDER.PAY_AMOUNT
	 * @return  the value of B2BBUSI.T_ORDER.PAY_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getPayAmount() {
		return payAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_ORDER.PAY_AMOUNT
	 * @param payAmount  the value for B2BBUSI.T_ORDER.PAY_AMOUNT
	 * @mbggenerated
	 */
	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}
}