
package com.ccic.salesapp.noncar.outService.esb.PaymentNoApply;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * ֧��������(�ո���ϵͳ)
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentNoApplyService", targetNamespace = "http://service.ccic.com/payment/paymentnoapply/intf", wsdlLocation = "file:/D:/vpn/ooo.wsdl")
public class PaymentNoApplyService
    extends Service
{

    private final static URL PAYMENTNOAPPLYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTNOAPPLYSERVICE_EXCEPTION;
    private final static QName PAYMENTNOAPPLYSERVICE_QNAME = new QName("http://service.ccic.com/payment/paymentnoapply/intf", "PaymentNoApplyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/vpn/ooo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTNOAPPLYSERVICE_WSDL_LOCATION = url;
        PAYMENTNOAPPLYSERVICE_EXCEPTION = e;
    }

    public PaymentNoApplyService() {
        super(__getWsdlLocation(), PAYMENTNOAPPLYSERVICE_QNAME);
    }

    public PaymentNoApplyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTNOAPPLYSERVICE_QNAME, features);
    }

    public PaymentNoApplyService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTNOAPPLYSERVICE_QNAME);
    }

    public PaymentNoApplyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTNOAPPLYSERVICE_QNAME, features);
    }

    public PaymentNoApplyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentNoApplyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentNoApply
     */
    @WebEndpoint(name = "PaymentNoApplyEndpoint")
    public PaymentNoApply getPaymentNoApplyEndpoint() {
        return super.getPort(new QName("http://service.ccic.com/payment/paymentnoapply/intf", "PaymentNoApplyEndpoint"), PaymentNoApply.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentNoApply
     */
    @WebEndpoint(name = "PaymentNoApplyEndpoint")
    public PaymentNoApply getPaymentNoApplyEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/payment/paymentnoapply/intf", "PaymentNoApplyEndpoint"), PaymentNoApply.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTNOAPPLYSERVICE_EXCEPTION!= null) {
            throw PAYMENTNOAPPLYSERVICE_EXCEPTION;
        }
        return PAYMENTNOAPPLYSERVICE_WSDL_LOCATION;
    }

}
