package com.ccic.salesapp.performance.domain.vo.dto;

import java.math.BigDecimal;
import java.util.Date;

public class PrpsPlanFeeDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.USERCODE
     *
     * @mbggenerated
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.REALPAYDATE
     *
     * @mbggenerated
     */
    private Date realpaydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE
     *
     * @mbggenerated
     */
    private BigDecimal payreffee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_CAR
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_NOCAR
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeNocar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_ACC
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_HEA
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeHea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeMS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_C
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeMSC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_NC
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeMSNc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_A
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeMSA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_H
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeMSH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeYS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_C
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeYSC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_NC
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeYSNc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_A
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeYSA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_H
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeYSH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_C
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_NC
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMNc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_A
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_H
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_C
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMsC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_NC
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMsNc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_A
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMsA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_H
     *
     * @mbggenerated
     */
    private BigDecimal payreffeeLMsH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.UPDATEDATE
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE1
     *
     * @mbggenerated
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE2
     *
     * @mbggenerated
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE3
     *
     * @mbggenerated
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE4
     *
     * @mbggenerated
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE5
     *
     * @mbggenerated
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE6
     *
     * @mbggenerated
     */
    private String attribute6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ID
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ID
     *
     * @param id the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.USERCODE
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.USERCODE
     *
     * @mbggenerated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.USERCODE
     *
     * @param usercode the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.USERCODE
     *
     * @mbggenerated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.REALPAYDATE
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.REALPAYDATE
     *
     * @mbggenerated
     */
    public Date getRealpaydate() {
        return realpaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.REALPAYDATE
     *
     * @param realpaydate the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.REALPAYDATE
     *
     * @mbggenerated
     */
    public void setRealpaydate(Date realpaydate) {
        this.realpaydate = realpaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffee() {
        return payreffee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE
     *
     * @param payreffee the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE
     *
     * @mbggenerated
     */
    public void setPayreffee(BigDecimal payreffee) {
        this.payreffee = payreffee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_CAR
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_CAR
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeCar() {
        return payreffeeCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_CAR
     *
     * @param payreffeeCar the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_CAR
     *
     * @mbggenerated
     */
    public void setPayreffeeCar(BigDecimal payreffeeCar) {
        this.payreffeeCar = payreffeeCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_NOCAR
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_NOCAR
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeNocar() {
        return payreffeeNocar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_NOCAR
     *
     * @param payreffeeNocar the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_NOCAR
     *
     * @mbggenerated
     */
    public void setPayreffeeNocar(BigDecimal payreffeeNocar) {
        this.payreffeeNocar = payreffeeNocar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_ACC
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_ACC
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeAcc() {
        return payreffeeAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_ACC
     *
     * @param payreffeeAcc the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_ACC
     *
     * @mbggenerated
     */
    public void setPayreffeeAcc(BigDecimal payreffeeAcc) {
        this.payreffeeAcc = payreffeeAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_HEA
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_HEA
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeHea() {
        return payreffeeHea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_HEA
     *
     * @param payreffeeHea the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_HEA
     *
     * @mbggenerated
     */
    public void setPayreffeeHea(BigDecimal payreffeeHea) {
        this.payreffeeHea = payreffeeHea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeMS() {
        return payreffeeMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S
     *
     * @param payreffeeMS the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S
     *
     * @mbggenerated
     */
    public void setPayreffeeMS(BigDecimal payreffeeMS) {
        this.payreffeeMS = payreffeeMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_C
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_C
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeMSC() {
        return payreffeeMSC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_C
     *
     * @param payreffeeMSC the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_C
     *
     * @mbggenerated
     */
    public void setPayreffeeMSC(BigDecimal payreffeeMSC) {
        this.payreffeeMSC = payreffeeMSC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_NC
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_NC
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeMSNc() {
        return payreffeeMSNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_NC
     *
     * @param payreffeeMSNc the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_NC
     *
     * @mbggenerated
     */
    public void setPayreffeeMSNc(BigDecimal payreffeeMSNc) {
        this.payreffeeMSNc = payreffeeMSNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_A
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_A
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeMSA() {
        return payreffeeMSA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_A
     *
     * @param payreffeeMSA the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_A
     *
     * @mbggenerated
     */
    public void setPayreffeeMSA(BigDecimal payreffeeMSA) {
        this.payreffeeMSA = payreffeeMSA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_H
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_H
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeMSH() {
        return payreffeeMSH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_H
     *
     * @param payreffeeMSH the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_M_S_H
     *
     * @mbggenerated
     */
    public void setPayreffeeMSH(BigDecimal payreffeeMSH) {
        this.payreffeeMSH = payreffeeMSH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeYS() {
        return payreffeeYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S
     *
     * @param payreffeeYS the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S
     *
     * @mbggenerated
     */
    public void setPayreffeeYS(BigDecimal payreffeeYS) {
        this.payreffeeYS = payreffeeYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_C
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_C
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeYSC() {
        return payreffeeYSC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_C
     *
     * @param payreffeeYSC the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_C
     *
     * @mbggenerated
     */
    public void setPayreffeeYSC(BigDecimal payreffeeYSC) {
        this.payreffeeYSC = payreffeeYSC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_NC
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_NC
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeYSNc() {
        return payreffeeYSNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_NC
     *
     * @param payreffeeYSNc the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_NC
     *
     * @mbggenerated
     */
    public void setPayreffeeYSNc(BigDecimal payreffeeYSNc) {
        this.payreffeeYSNc = payreffeeYSNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_A
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_A
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeYSA() {
        return payreffeeYSA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_A
     *
     * @param payreffeeYSA the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_A
     *
     * @mbggenerated
     */
    public void setPayreffeeYSA(BigDecimal payreffeeYSA) {
        this.payreffeeYSA = payreffeeYSA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_H
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_H
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeYSH() {
        return payreffeeYSH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_H
     *
     * @param payreffeeYSH the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_Y_S_H
     *
     * @mbggenerated
     */
    public void setPayreffeeYSH(BigDecimal payreffeeYSH) {
        this.payreffeeYSH = payreffeeYSH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLM() {
        return payreffeeLM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M
     *
     * @param payreffeeLM the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M
     *
     * @mbggenerated
     */
    public void setPayreffeeLM(BigDecimal payreffeeLM) {
        this.payreffeeLM = payreffeeLM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_C
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_C
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMC() {
        return payreffeeLMC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_C
     *
     * @param payreffeeLMC the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_C
     *
     * @mbggenerated
     */
    public void setPayreffeeLMC(BigDecimal payreffeeLMC) {
        this.payreffeeLMC = payreffeeLMC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_NC
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_NC
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMNc() {
        return payreffeeLMNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_NC
     *
     * @param payreffeeLMNc the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_NC
     *
     * @mbggenerated
     */
    public void setPayreffeeLMNc(BigDecimal payreffeeLMNc) {
        this.payreffeeLMNc = payreffeeLMNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_A
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_A
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMA() {
        return payreffeeLMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_A
     *
     * @param payreffeeLMA the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_A
     *
     * @mbggenerated
     */
    public void setPayreffeeLMA(BigDecimal payreffeeLMA) {
        this.payreffeeLMA = payreffeeLMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_H
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_H
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMH() {
        return payreffeeLMH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_H
     *
     * @param payreffeeLMH the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_M_H
     *
     * @mbggenerated
     */
    public void setPayreffeeLMH(BigDecimal payreffeeLMH) {
        this.payreffeeLMH = payreffeeLMH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMs() {
        return payreffeeLMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS
     *
     * @param payreffeeLMs the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS
     *
     * @mbggenerated
     */
    public void setPayreffeeLMs(BigDecimal payreffeeLMs) {
        this.payreffeeLMs = payreffeeLMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_C
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_C
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMsC() {
        return payreffeeLMsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_C
     *
     * @param payreffeeLMsC the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_C
     *
     * @mbggenerated
     */
    public void setPayreffeeLMsC(BigDecimal payreffeeLMsC) {
        this.payreffeeLMsC = payreffeeLMsC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_NC
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_NC
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMsNc() {
        return payreffeeLMsNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_NC
     *
     * @param payreffeeLMsNc the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_NC
     *
     * @mbggenerated
     */
    public void setPayreffeeLMsNc(BigDecimal payreffeeLMsNc) {
        this.payreffeeLMsNc = payreffeeLMsNc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_A
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_A
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMsA() {
        return payreffeeLMsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_A
     *
     * @param payreffeeLMsA the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_A
     *
     * @mbggenerated
     */
    public void setPayreffeeLMsA(BigDecimal payreffeeLMsA) {
        this.payreffeeLMsA = payreffeeLMsA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_H
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_H
     *
     * @mbggenerated
     */
    public BigDecimal getPayreffeeLMsH() {
        return payreffeeLMsH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_H
     *
     * @param payreffeeLMsH the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.PAYREFFEE_L_MS_H
     *
     * @mbggenerated
     */
    public void setPayreffeeLMsH(BigDecimal payreffeeLMsH) {
        this.payreffeeLMsH = payreffeeLMsH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.UPDATEDATE
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.UPDATEDATE
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.UPDATEDATE
     *
     * @param updatedate the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.UPDATEDATE
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE1
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE1
     *
     * @mbggenerated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE1
     *
     * @param attribute1 the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE1
     *
     * @mbggenerated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE2
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE2
     *
     * @mbggenerated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE2
     *
     * @param attribute2 the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE2
     *
     * @mbggenerated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE3
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE3
     *
     * @mbggenerated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE3
     *
     * @param attribute3 the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE3
     *
     * @mbggenerated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE4
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE4
     *
     * @mbggenerated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE4
     *
     * @param attribute4 the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE4
     *
     * @mbggenerated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE5
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE5
     *
     * @mbggenerated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE5
     *
     * @param attribute5 the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE5
     *
     * @mbggenerated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE6
     *
     * @return the value of B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE6
     *
     * @mbggenerated
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE6
     *
     * @param attribute6 the value for B2BBUSI.T_APP_S_PRPSPLANFEE_DAY.ATTRIBUTE6
     *
     * @mbggenerated
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }
}