package com.ccic.salesapp.performance.domain.vo.dto;

public class SaleLawPersonDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CALCMONTH
     *
     * @mbggenerated
     */
    private String calcmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.USERCODE
     *
     * @mbggenerated
     */
    private String usercode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CALCMONTH
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CALCMONTH
     *
     * @mbggenerated
     */
    public String getCalcmonth() {
        return calcmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CALCMONTH
     *
     * @param calcmonth the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CALCMONTH
     *
     * @mbggenerated
     */
    public void setCalcmonth(String calcmonth) {
        this.calcmonth = calcmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.USERCODE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.USERCODE
     *
     * @mbggenerated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.USERCODE
     *
     * @param usercode the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.USERCODE
     *
     * @mbggenerated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }
}