package com.ccic.salesapp.performance.domain.vo.dto;

import java.math.BigDecimal;
import java.util.Date;

public class SaleLawPersonDetail extends SaleLawPersonDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSTANDARDPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal monthstandardpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSUMPREMIUMPLAN
     *
     * @mbggenerated
     */
    private BigDecimal monthsumpremiumplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHPREMIUMREACHRATE
     *
     * @mbggenerated
     */
    private BigDecimal monthpremiumreachrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CURRENTMONTHPREMIUMPLAN
     *
     * @mbggenerated
     */
    private BigDecimal currentmonthpremiumplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.SUMSTANDARDPREMIUM
     *
     * @mbggenerated
     */
    private BigDecimal sumstandardpremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARSUMPREMIUMPLAN
     *
     * @mbggenerated
     */
    private BigDecimal yearsumpremiumplan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARPREMIUMREACHRATE
     *
     * @mbggenerated
     */
    private BigDecimal yearpremiumreachrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.UPDATEDATE
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSTANDARDPREMIUM
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSTANDARDPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getMonthstandardpremium() {
        return monthstandardpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSTANDARDPREMIUM
     *
     * @param monthstandardpremium the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSTANDARDPREMIUM
     *
     * @mbggenerated
     */
    public void setMonthstandardpremium(BigDecimal monthstandardpremium) {
        this.monthstandardpremium = monthstandardpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSUMPREMIUMPLAN
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSUMPREMIUMPLAN
     *
     * @mbggenerated
     */
    public BigDecimal getMonthsumpremiumplan() {
        return monthsumpremiumplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSUMPREMIUMPLAN
     *
     * @param monthsumpremiumplan the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHSUMPREMIUMPLAN
     *
     * @mbggenerated
     */
    public void setMonthsumpremiumplan(BigDecimal monthsumpremiumplan) {
        this.monthsumpremiumplan = monthsumpremiumplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHPREMIUMREACHRATE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHPREMIUMREACHRATE
     *
     * @mbggenerated
     */
    public BigDecimal getMonthpremiumreachrate() {
        return monthpremiumreachrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHPREMIUMREACHRATE
     *
     * @param monthpremiumreachrate the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.MONTHPREMIUMREACHRATE
     *
     * @mbggenerated
     */
    public void setMonthpremiumreachrate(BigDecimal monthpremiumreachrate) {
        this.monthpremiumreachrate = monthpremiumreachrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CURRENTMONTHPREMIUMPLAN
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CURRENTMONTHPREMIUMPLAN
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentmonthpremiumplan() {
        return currentmonthpremiumplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CURRENTMONTHPREMIUMPLAN
     *
     * @param currentmonthpremiumplan the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.CURRENTMONTHPREMIUMPLAN
     *
     * @mbggenerated
     */
    public void setCurrentmonthpremiumplan(BigDecimal currentmonthpremiumplan) {
        this.currentmonthpremiumplan = currentmonthpremiumplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.SUMSTANDARDPREMIUM
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.SUMSTANDARDPREMIUM
     *
     * @mbggenerated
     */
    public BigDecimal getSumstandardpremium() {
        return sumstandardpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.SUMSTANDARDPREMIUM
     *
     * @param sumstandardpremium the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.SUMSTANDARDPREMIUM
     *
     * @mbggenerated
     */
    public void setSumstandardpremium(BigDecimal sumstandardpremium) {
        this.sumstandardpremium = sumstandardpremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARSUMPREMIUMPLAN
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARSUMPREMIUMPLAN
     *
     * @mbggenerated
     */
    public BigDecimal getYearsumpremiumplan() {
        return yearsumpremiumplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARSUMPREMIUMPLAN
     *
     * @param yearsumpremiumplan the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARSUMPREMIUMPLAN
     *
     * @mbggenerated
     */
    public void setYearsumpremiumplan(BigDecimal yearsumpremiumplan) {
        this.yearsumpremiumplan = yearsumpremiumplan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARPREMIUMREACHRATE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARPREMIUMREACHRATE
     *
     * @mbggenerated
     */
    public BigDecimal getYearpremiumreachrate() {
        return yearpremiumreachrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARPREMIUMREACHRATE
     *
     * @param yearpremiumreachrate the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.YEARPREMIUMREACHRATE
     *
     * @mbggenerated
     */
    public void setYearpremiumreachrate(BigDecimal yearpremiumreachrate) {
        this.yearpremiumreachrate = yearpremiumreachrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.UPDATEDATE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.UPDATEDATE
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.UPDATEDATE
     *
     * @param updatedate the value for B2BBUSI.T_APP_S_SALELAW_PERSONDETAIL.UPDATEDATE
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}