package com.ccic.salesapp.performance.domain.vo.dto;

import java.util.Date;

public class SalelawPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.USERCODE
     *
     * @mbggenerated
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.COMCODE
     *
     * @mbggenerated
     */
    private String comcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.COMCANME
     *
     * @mbggenerated
     */
    private String comcanme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELCODE
     *
     * @mbggenerated
     */
    private String channelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELNAME
     *
     * @mbggenerated
     */
    private String channelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCODE
     *
     * @mbggenerated
     */
    private String teamcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCNAME
     *
     * @mbggenerated
     */
    private String teamcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPEID
     *
     * @mbggenerated
     */
    private String persontypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPENAME
     *
     * @mbggenerated
     */
    private String persontypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYID
     *
     * @mbggenerated
     */
    private String dutyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYNAME
     *
     * @mbggenerated
     */
    private String dutyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.RANKCODE
     *
     * @mbggenerated
     */
    private String rankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.RANKNAME
     *
     * @mbggenerated
     */
    private String rankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.ABTYPE
     *
     * @mbggenerated
     */
    private String abtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2BBUSI.T_APP_S_SALELAW_PERSON.UPDATEDATE
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.USERCODE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.USERCODE
     *
     * @mbggenerated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.USERCODE
     *
     * @param usercode the value for B2BBUSI.T_APP_S_SALELAW_PERSON.USERCODE
     *
     * @mbggenerated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.USERNAME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.USERNAME
     *
     * @param username the value for B2BBUSI.T_APP_S_SALELAW_PERSON.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.COMCODE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.COMCODE
     *
     * @mbggenerated
     */
    public String getComcode() {
        return comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.COMCODE
     *
     * @param comcode the value for B2BBUSI.T_APP_S_SALELAW_PERSON.COMCODE
     *
     * @mbggenerated
     */
    public void setComcode(String comcode) {
        this.comcode = comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.COMCANME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.COMCANME
     *
     * @mbggenerated
     */
    public String getComcanme() {
        return comcanme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.COMCANME
     *
     * @param comcanme the value for B2BBUSI.T_APP_S_SALELAW_PERSON.COMCANME
     *
     * @mbggenerated
     */
    public void setComcanme(String comcanme) {
        this.comcanme = comcanme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELCODE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELCODE
     *
     * @mbggenerated
     */
    public String getChannelcode() {
        return channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELCODE
     *
     * @param channelcode the value for B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELCODE
     *
     * @mbggenerated
     */
    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELNAME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELNAME
     *
     * @mbggenerated
     */
    public String getChannelname() {
        return channelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELNAME
     *
     * @param channelname the value for B2BBUSI.T_APP_S_SALELAW_PERSON.CHANNELNAME
     *
     * @mbggenerated
     */
    public void setChannelname(String channelname) {
        this.channelname = channelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCODE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCODE
     *
     * @mbggenerated
     */
    public String getTeamcode() {
        return teamcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCODE
     *
     * @param teamcode the value for B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCODE
     *
     * @mbggenerated
     */
    public void setTeamcode(String teamcode) {
        this.teamcode = teamcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCNAME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCNAME
     *
     * @mbggenerated
     */
    public String getTeamcname() {
        return teamcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCNAME
     *
     * @param teamcname the value for B2BBUSI.T_APP_S_SALELAW_PERSON.TEAMCNAME
     *
     * @mbggenerated
     */
    public void setTeamcname(String teamcname) {
        this.teamcname = teamcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPEID
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPEID
     *
     * @mbggenerated
     */
    public String getPersontypeid() {
        return persontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPEID
     *
     * @param persontypeid the value for B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPEID
     *
     * @mbggenerated
     */
    public void setPersontypeid(String persontypeid) {
        this.persontypeid = persontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPENAME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPENAME
     *
     * @mbggenerated
     */
    public String getPersontypename() {
        return persontypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPENAME
     *
     * @param persontypename the value for B2BBUSI.T_APP_S_SALELAW_PERSON.PERSONTYPENAME
     *
     * @mbggenerated
     */
    public void setPersontypename(String persontypename) {
        this.persontypename = persontypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYID
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYID
     *
     * @mbggenerated
     */
    public String getDutyid() {
        return dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYID
     *
     * @param dutyid the value for B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYID
     *
     * @mbggenerated
     */
    public void setDutyid(String dutyid) {
        this.dutyid = dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYNAME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYNAME
     *
     * @mbggenerated
     */
    public String getDutyname() {
        return dutyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYNAME
     *
     * @param dutyname the value for B2BBUSI.T_APP_S_SALELAW_PERSON.DUTYNAME
     *
     * @mbggenerated
     */
    public void setDutyname(String dutyname) {
        this.dutyname = dutyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.RANKCODE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.RANKCODE
     *
     * @mbggenerated
     */
    public String getRankcode() {
        return rankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.RANKCODE
     *
     * @param rankcode the value for B2BBUSI.T_APP_S_SALELAW_PERSON.RANKCODE
     *
     * @mbggenerated
     */
    public void setRankcode(String rankcode) {
        this.rankcode = rankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.RANKNAME
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.RANKNAME
     *
     * @mbggenerated
     */
    public String getRankname() {
        return rankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.RANKNAME
     *
     * @param rankname the value for B2BBUSI.T_APP_S_SALELAW_PERSON.RANKNAME
     *
     * @mbggenerated
     */
    public void setRankname(String rankname) {
        this.rankname = rankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.ABTYPE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.ABTYPE
     *
     * @mbggenerated
     */
    public String getAbtype() {
        return abtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.ABTYPE
     *
     * @param abtype the value for B2BBUSI.T_APP_S_SALELAW_PERSON.ABTYPE
     *
     * @mbggenerated
     */
    public void setAbtype(String abtype) {
        this.abtype = abtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.UPDATEDATE
     *
     * @return the value of B2BBUSI.T_APP_S_SALELAW_PERSON.UPDATEDATE
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2BBUSI.T_APP_S_SALELAW_PERSON.UPDATEDATE
     *
     * @param updatedate the value for B2BBUSI.T_APP_S_SALELAW_PERSON.UPDATEDATE
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}