package com.ccic.salesapp.noncar.outService.esb.quotetoproposal.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-03-03T11:17:11.241+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/car/quotetoproposal/intf", name = "QuoteToProposal")
@XmlSeeAlso({com.ccic.salesapp.noncar.outService.esb.quotetoproposal.bean.ObjectFactory.class, com.ccic.salesapp.noncar.outService.esb.quotetoproposal.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QuoteToProposal {

    @WebResult(name = "QuoteToProposalResponse", targetNamespace = "http://service.ccic.com/car/quotetoproposal/bean", partName = "QuoteToProposalResponse")
    @WebMethod(operationName = "QuoteToProposal", action = "/car/QuoteToProposal")
    public com.ccic.salesapp.noncar.outService.esb.quotetoproposal.bean.QuoteToProposalResponse quoteToProposal(
        @WebParam(partName = "QuoteToProposalRequest", name = "QuoteToProposalRequest", targetNamespace = "http://service.ccic.com/car/quotetoproposal/bean")
        com.ccic.salesapp.noncar.outService.esb.quotetoproposal.bean.QuoteToProposalRequest quoteToProposalRequest
    );
}
