package com.ccic.salesapp.noncar.outService.esb.quotetoproposal.intf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2017-03-03T11:17:11.370+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "QuoteProposalService", 
                  wsdlLocation = "http://10.1.13.193:15507/QuoteProposalService?wsdl",
                  targetNamespace = "http://service.ccic.com/car/quotetoproposal/intf") 
public class QuoteProposalService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/car/quotetoproposal/intf", "QuoteProposalService");
    public final static QName QuoteProposalEndpoint = new QName("http://service.ccic.com/car/quotetoproposal/intf", "QuoteProposalEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://10.1.13.193:15507/QuoteProposalService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QuoteProposalService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.1.13.193:15507/QuoteProposalService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QuoteProposalService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QuoteProposalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuoteProposalService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QuoteToProposal
     */
    @WebEndpoint(name = "QuoteProposalEndpoint")
    public QuoteToProposal getQuoteProposalEndpoint() {
        return super.getPort(QuoteProposalEndpoint, QuoteToProposal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteToProposal
     */
    @WebEndpoint(name = "QuoteProposalEndpoint")
    public QuoteToProposal getQuoteProposalEndpoint(WebServiceFeature... features) {
        return super.getPort(QuoteProposalEndpoint, QuoteToProposal.class, features);
    }

}
