
package com.ccic.salesapp.performance.outService.esb.PlanFeeInquiry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlanFeeInquiryService", targetNamespace = "http://service.ccic.com/agent/planFee/intf", wsdlLocation = "file:/D:/vpn/www.wsdl")
public class PlanFeeInquiryService
    extends Service
{

    private final static URL PLANFEEINQUIRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLANFEEINQUIRYSERVICE_EXCEPTION;
    private final static QName PLANFEEINQUIRYSERVICE_QNAME = new QName("http://service.ccic.com/agent/planFee/intf", "PlanFeeInquiryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/vpn/www.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLANFEEINQUIRYSERVICE_WSDL_LOCATION = url;
        PLANFEEINQUIRYSERVICE_EXCEPTION = e;
    }

    public PlanFeeInquiryService() {
        super(__getWsdlLocation(), PLANFEEINQUIRYSERVICE_QNAME);
    }

    public PlanFeeInquiryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLANFEEINQUIRYSERVICE_QNAME, features);
    }

    public PlanFeeInquiryService(URL wsdlLocation) {
        super(wsdlLocation, PLANFEEINQUIRYSERVICE_QNAME);
    }

    public PlanFeeInquiryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLANFEEINQUIRYSERVICE_QNAME, features);
    }

    public PlanFeeInquiryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlanFeeInquiryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PlanFeeInquiryPort
     */
    @WebEndpoint(name = "PlanFeeInquiryPort")
    public PlanFeeInquiryPort getPlanFeeInquiryPort() {
        return super.getPort(new QName("http://service.ccic.com/agent/planFee/intf", "PlanFeeInquiryPort"), PlanFeeInquiryPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlanFeeInquiryPort
     */
    @WebEndpoint(name = "PlanFeeInquiryPort")
    public PlanFeeInquiryPort getPlanFeeInquiryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/agent/planFee/intf", "PlanFeeInquiryPort"), PlanFeeInquiryPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLANFEEINQUIRYSERVICE_EXCEPTION!= null) {
            throw PLANFEEINQUIRYSERVICE_EXCEPTION;
        }
        return PLANFEEINQUIRYSERVICE_WSDL_LOCATION;
    }

}
