
package com.ccic.salesapp.performance.outService.esb.PlanFeeInquiry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlanFeeInquiryPort", targetNamespace = "http://service.ccic.com/agent/planFee/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlanFeeInquiryPort {


    /**
     * 
     * @param planFeeInquiryRequest
     * @return
     *     returns com.esb.PlanFeeInquiryResponse
     */
    @WebMethod(operationName = "PlanFeeInquiry", action = "/planFee/planFeeInquiry")
    @WebResult(name = "PlanFeeInquiryResponse", targetNamespace = "http://service.ccic.com/agent/planFee/bean", partName = "PlanFeeInquiryResponse")
    public PlanFeeInquiryResponse planFeeInquiry(
        @WebParam(name = "PlanFeeInquiryRequest", targetNamespace = "http://service.ccic.com/agent/planFee/bean", partName = "PlanFeeInquiryRequest")
        PlanFeeInquiryRequest planFeeInquiryRequest);

}
