
package com.ccic.salesapp.noncar.outService.esb.einvoiceInquiry.intf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EinvoiceInquiryServiceService", targetNamespace = "http://service.ccic.com/payment/eInvoiceInquiry/intf", wsdlLocation = "file:/D:/src/EinvoiceInquiryService.wsdl")
public class EinvoiceInquiryServiceService
    extends Service
{

    private final static URL EINVOICEINQUIRYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EINVOICEINQUIRYSERVICESERVICE_EXCEPTION;
    private final static QName EINVOICEINQUIRYSERVICESERVICE_QNAME = new QName("http://service.ccic.com/payment/eInvoiceInquiry/intf", "EinvoiceInquiryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/src/EinvoiceInquiryService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EINVOICEINQUIRYSERVICESERVICE_WSDL_LOCATION = url;
        EINVOICEINQUIRYSERVICESERVICE_EXCEPTION = e;
    }

    public EinvoiceInquiryServiceService() {
        super(__getWsdlLocation(), EINVOICEINQUIRYSERVICESERVICE_QNAME);
    }

    public EinvoiceInquiryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EINVOICEINQUIRYSERVICESERVICE_QNAME, features);
    }

    public EinvoiceInquiryServiceService(URL wsdlLocation) {
        super(wsdlLocation, EINVOICEINQUIRYSERVICESERVICE_QNAME);
    }

    public EinvoiceInquiryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EINVOICEINQUIRYSERVICESERVICE_QNAME, features);
    }

    public EinvoiceInquiryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EinvoiceInquiryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EinvoiceInquiryServicePort
     */
    @WebEndpoint(name = "EinvoiceInquiryServicePort")
    public EinvoiceInquiryServicePort getEinvoiceInquiryServicePort() {
        return super.getPort(new QName("http://service.ccic.com/payment/eInvoiceInquiry/intf", "EinvoiceInquiryServicePort"), EinvoiceInquiryServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EinvoiceInquiryServicePort
     */
    @WebEndpoint(name = "EinvoiceInquiryServicePort")
    public EinvoiceInquiryServicePort getEinvoiceInquiryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/payment/eInvoiceInquiry/intf", "EinvoiceInquiryServicePort"), EinvoiceInquiryServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EINVOICEINQUIRYSERVICESERVICE_EXCEPTION!= null) {
            throw EINVOICEINQUIRYSERVICESERVICE_EXCEPTION;
        }
        return EINVOICEINQUIRYSERVICESERVICE_WSDL_LOCATION;
    }

}
