
package com.ccic.salesapp.noncar.outService.esb.einvoiceInquiry.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ccic.salesapp.noncar.outService.esb.einvoiceInquiry.bean.EinvoiceInquiryRequest;
import com.ccic.salesapp.noncar.outService.esb.einvoiceInquiry.bean.EinvoiceInquiryResponse;
import com.ccic.salesapp.noncar.outService.esb.einvoiceInquiry.bean.ObjectFactory;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EinvoiceInquiryServicePort", targetNamespace = "http://service.ccic.com/payment/eInvoiceInquiry/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EinvoiceInquiryServicePort {


    /**
     * 
     * @param einvoiceInquiryRequest
     * @return
     *     returns com.salesapp.webservice.EinvoiceInquiryResponse
     */
    @WebMethod(operationName = "EinvoiceInquiryService", action = "/einvoice/inquiryInvoice")
    @WebResult(name = "EinvoiceInquiryResponse", targetNamespace = "http://service.ccic.com/payment/eInvoiceInquiry/bean", partName = "EinvoiceInquiryResponse")
    public EinvoiceInquiryResponse einvoiceInquiryService(
        @WebParam(name = "EinvoiceInquiryRequest", targetNamespace = "http://service.ccic.com/payment/eInvoiceInquiry/bean", partName = "EinvoiceInquiryRequest")
        EinvoiceInquiryRequest einvoiceInquiryRequest);

}
