package com.ccic.salesapp.noncar.outService.esb.entBaseInfoInquiry.intf;

import com.ccic.salessapp.common.utils.PropertiesUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T15:42:49.428+08:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "EntBaseInfoInquiryService",
                  wsdlLocation = "http://10.1.13.183:7001/ecif/services/EntBaseInfoInquiry?wsdl",
                  targetNamespace = "http://service.ccic.com/ecif/entbaseinfoinquiry/intf")
public class EntBaseInfoInquiryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/ecif/entbaseinfoinquiry/intf", "EntBaseInfoInquiryService");
    public final static QName EntBaseInfoInquiryEndpoint = new QName("http://service.ccic.com/ecif/entbaseinfoinquiry/intf", "EntBaseInfoInquiryEndpoint");
    static {
        URL url = null;
        try {
            String propertiesValue = PropertiesUtil.getProperty("esb.ecif.claimStatusInquiry", "");

            url = new URL(propertiesValue);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EntBaseInfoInquiryService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/project-data/ccic-salesapp-customer/src/main/java/com/ccic/salesapp/customer/outService/esb/ecif/entBaseInfoInquiry/EntBaseInfoInquiry.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EntBaseInfoInquiryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EntBaseInfoInquiryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntBaseInfoInquiryService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EntBaseInfoInquiryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EntBaseInfoInquiryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EntBaseInfoInquiryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EntBaseInfoInquiry
     */
    @WebEndpoint(name = "EntBaseInfoInquiryEndpoint")
    public EntBaseInfoInquiry getEntBaseInfoInquiryEndpoint() {
        return super.getPort(EntBaseInfoInquiryEndpoint, EntBaseInfoInquiry.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntBaseInfoInquiry
     */
    @WebEndpoint(name = "EntBaseInfoInquiryEndpoint")
    public EntBaseInfoInquiry getEntBaseInfoInquiryEndpoint(WebServiceFeature... features) {
        return super.getPort(EntBaseInfoInquiryEndpoint, EntBaseInfoInquiry.class, features);
    }

}
