package com.ccic.salesapp.noncar.outService.esb.userservice.userinquiry.intf;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserInquiryService service = new UserInquiryService();
 * UserInquiryService portType = service.getUserInquiryEndpoint();
 * portType.getUser(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserInquiryService", targetNamespace = "http://service.ccic.com/userservice/userInquiry/intf/", wsdlLocation = "http://10.1.13.193:15006/UserInquiryService?wsdl")
public class UserInquiryService_Service extends Service {

	private final static URL USERINQUIRYSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(UserInquiryService_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = UserInquiryService_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.1.13.193:15006/UserInquiryService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.1.13.193:15006/UserInquiryService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERINQUIRYSERVICE_WSDL_LOCATION = url;
	}

	public UserInquiryService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserInquiryService_Service() {
		super(USERINQUIRYSERVICE_WSDL_LOCATION, new QName(
				"http://service.ccic.com/userservice/userInquiry/intf/",
				"UserInquiryService"));
	}

	/**
	 * 
	 * @return returns UserInquiryService
	 */
	@WebEndpoint(name = "UserInquiryEndpoint")
	public UserInquiryService getUserInquiryEndpoint() {
		return super.getPort(new QName(
				"http://service.ccic.com/userservice/userInquiry/intf/",
				"UserInquiryEndpoint"), UserInquiryService.class);
	}

}
