package com.ccic.salesapp.noncar.outService.esb.userservice.userinquiry.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.ccic.salesapp.noncar.outService.esb.userservice.bean.UserInquiryRequest;
import com.ccic.salesapp.noncar.outService.esb.userservice.bean.UserInquiryResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserInquiryService", targetNamespace = "http://service.ccic.com/userservice/userInquiry/intf/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserInquiryService {

	/**
	 * 
	 * @param userInquiryRequest
	 * @return returns com.ccic.service.userservice.bean.UserInquiryResponse
	 */
	@WebMethod(action = "/userservice/userinquiryservice")
	@WebResult(name = "UserInquiryResponse", targetNamespace = "http://service.ccic.com/userservice/bean", partName = "UserInquiryResponse")
	public UserInquiryResponse getUser(
			@WebParam(name = "UserInquiryRequest", targetNamespace = "http://service.ccic.com/userservice/bean", partName = "UserInquiryRequest")
			UserInquiryRequest userInquiryRequest);

}
