spring:
  application:
    name: tl-common-components
server:
  port: 8114
management:
  security:
    enabled: false
eureka:
  client:
    registry-fetch-interval-seconds: 5 
    service-url:
      defaultZone: http://127.0.0.1:8111/eureka/
