package com.ccic.salesapp.noncar.outService.esb.paysuccess;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-12-20T11:03:14.559+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/payment/paysuccess/intf", name = "PaySuccess")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaySuccess {

    @WebResult(name = "PaySuccessResponse", targetNamespace = "http://service.ccic.com/payment/paysuccess/bean", partName = "PaySuccessResponse")
    @WebMethod(action = "/payment/paysuccess")
    public PaySuccessResponse paySuccess(
        @WebParam(partName = "PaySuccessRequest", name = "PaySuccessRequest", targetNamespace = "http://service.ccic.com/payment/paysuccess/bean")
        PaySuccessRequest paySuccessRequest
    );
}
