
package com.ccic.salesapp.noncar.outService.esb.paysuccess;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaySuccessNoticeService", targetNamespace = "http://service.ccic.com/pss/paySuccess/intf", wsdlLocation = "file:/Users/yanshuai/Desktop/qqqw/a.wsdl")
public class PaySuccessNoticeService
    extends Service
{

    private final static URL PAYSUCCESSNOTICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYSUCCESSNOTICESERVICE_EXCEPTION;
    private final static QName PAYSUCCESSNOTICESERVICE_QNAME = new QName("http://service.ccic.com/pss/paySuccess/intf", "PaySuccessNoticeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/yanshuai/Desktop/qqqw/a.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYSUCCESSNOTICESERVICE_WSDL_LOCATION = url;
        PAYSUCCESSNOTICESERVICE_EXCEPTION = e;
    }

    public PaySuccessNoticeService() {
        super(__getWsdlLocation(), PAYSUCCESSNOTICESERVICE_QNAME);
    }

    public PaySuccessNoticeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYSUCCESSNOTICESERVICE_QNAME, features);
    }

    public PaySuccessNoticeService(URL wsdlLocation) {
        super(wsdlLocation, PAYSUCCESSNOTICESERVICE_QNAME);
    }

    public PaySuccessNoticeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYSUCCESSNOTICESERVICE_QNAME, features);
    }

    public PaySuccessNoticeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaySuccessNoticeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaySuccessNoticePort
     */
    @WebEndpoint(name = "PaySuccessNoticePort")
    public PaySuccessNoticePort getPaySuccessNoticePort() {
        return super.getPort(new QName("http://service.ccic.com/pss/paySuccess/intf", "PaySuccessNoticePort"), PaySuccessNoticePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaySuccessNoticePort
     */
    @WebEndpoint(name = "PaySuccessNoticePort")
    public PaySuccessNoticePort getPaySuccessNoticePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/pss/paySuccess/intf", "PaySuccessNoticePort"), PaySuccessNoticePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYSUCCESSNOTICESERVICE_EXCEPTION!= null) {
            throw PAYSUCCESSNOTICESERVICE_EXCEPTION;
        }
        return PAYSUCCESSNOTICESERVICE_WSDL_LOCATION;
    }

}
