
package com.ccic.salesapp.noncar.outService.esb.paysuccess;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaySuccessNoticePort", targetNamespace = "http://service.ccic.com/pss/paySuccess/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaySuccessNoticePort {


    /**
     * 
     * @param paySuccessNoticeRequest
     * @return
     *     returns com.yan.webService.PaySuccessNoticeResponse
     */
    @WebMethod(operationName = "PaySuccessNotice", action = "/pss/paySuccess")
    @WebResult(name = "PaySuccessNoticeResponse", targetNamespace = "http://service.ccic.com/pss/paySuccess/bean", partName = "PaySuccessNoticeResponse")
    public PaySuccessNoticeResponse paySuccessNotice(
        @WebParam(name = "PaySuccessNoticeRequest", targetNamespace = "http://service.ccic.com/pss/paySuccess/bean", partName = "PaySuccessNoticeRequest")
        PaySuccessNoticeRequest paySuccessNoticeRequest);

}
