package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;
import java.util.Date;

public class Applicant {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.ADDRESS
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.AGE
	 * @mbggenerated
	 */
	private Long age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.BIRTH_DATE
	 * @mbggenerated
	 */
	private Date birthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.CUST_NO
	 * @mbggenerated
	 */
	private String custNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.EMAIL
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.IDENTITY_NO
	 * @mbggenerated
	 */
	private String identityNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.IDENTITY_TYPE
	 * @mbggenerated
	 */
	private String identityType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.NAME
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.PHONE
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.POST_CODE
	 * @mbggenerated
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.SEX
	 * @mbggenerated
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.UNIT_TYPE
	 * @mbggenerated
	 */
	private String unitType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.INSURED_NATURE
	 * @mbggenerated
	 */
	private String insuredNature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APP_NATION
	 * @mbggenerated
	 */
	private String appNation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_COM
	 * @mbggenerated
	 */
	private String appIdentifyCom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_START_DATE
	 * @mbggenerated
	 */
	private String appIdentifyStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_END_DATE
	 * @mbggenerated
	 */
	private String appIdentifyEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.PROVINCECODE
	 * @mbggenerated
	 */
	private String provincecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.COUNTYCODE
	 * @mbggenerated
	 */
	private String countycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.PREFECTURECODE
	 * @mbggenerated
	 */
	private String prefecturecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.ADDEDVALUETAX_ID
	 * @mbggenerated
	 */
	private BigDecimal addedvaluetaxId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APPICFLAG
	 * @mbggenerated
	 */
	private String appicflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.IS_NEED_E_INVOICE
	 * @mbggenerated
	 */
	private String isNeedEInvoice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APP_CERTIFICATE_START_DATE
	 * @mbggenerated
	 */
	private String appCertificateStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APP_CERTIFICATE_END_DATE
	 * @mbggenerated
	 */
	private String appCertificateEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APPLICANT_OCCUPATION
	 * @mbggenerated
	 */
	private String applicantOccupation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_NAME
	 * @mbggenerated
	 */
	private String customerAgentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATETYPE
	 * @mbggenerated
	 */
	private String customerAgentCertificatetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATENUM
	 * @mbggenerated
	 */
	private String customerAgentCertificatenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.PAYER_ACCOUNT_NAME
	 * @mbggenerated
	 */
	private String payerAccountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE
	 * @mbggenerated
	 */
	private String applicantPayerReType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE_REMARK
	 * @mbggenerated
	 */
	private String applicantPayerReTypeRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.NATIONALITY
	 * @mbggenerated
	 */
	private String nationality;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.UNIT_OCCUPATION_NAME
	 * @mbggenerated
	 */
	private String unitOccupationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.PHONE_HOLDER_NAME
	 * @mbggenerated
	 */
	private String phoneHolderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.PHONE_HOLDER_IDNO
	 * @mbggenerated
	 */
	private String phoneHolderIdno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_APPLICANT.IS_PHONE_HOLDER
	 * @mbggenerated
	 */
	private String isPhoneHolder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.ID
	 * @return  the value of B2BBUSI.T_APPLICANT.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.ID
	 * @param id  the value for B2BBUSI.T_APPLICANT.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.ADDRESS
	 * @return  the value of B2BBUSI.T_APPLICANT.ADDRESS
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.ADDRESS
	 * @param address  the value for B2BBUSI.T_APPLICANT.ADDRESS
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.AGE
	 * @return  the value of B2BBUSI.T_APPLICANT.AGE
	 * @mbggenerated
	 */
	public Long getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.AGE
	 * @param age  the value for B2BBUSI.T_APPLICANT.AGE
	 * @mbggenerated
	 */
	public void setAge(Long age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.BIRTH_DATE
	 * @return  the value of B2BBUSI.T_APPLICANT.BIRTH_DATE
	 * @mbggenerated
	 */
	public Date getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.BIRTH_DATE
	 * @param birthDate  the value for B2BBUSI.T_APPLICANT.BIRTH_DATE
	 * @mbggenerated
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.CUST_NO
	 * @return  the value of B2BBUSI.T_APPLICANT.CUST_NO
	 * @mbggenerated
	 */
	public String getCustNo() {
		return custNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.CUST_NO
	 * @param custNo  the value for B2BBUSI.T_APPLICANT.CUST_NO
	 * @mbggenerated
	 */
	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.EMAIL
	 * @return  the value of B2BBUSI.T_APPLICANT.EMAIL
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.EMAIL
	 * @param email  the value for B2BBUSI.T_APPLICANT.EMAIL
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.IDENTITY_NO
	 * @return  the value of B2BBUSI.T_APPLICANT.IDENTITY_NO
	 * @mbggenerated
	 */
	public String getIdentityNo() {
		return identityNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.IDENTITY_NO
	 * @param identityNo  the value for B2BBUSI.T_APPLICANT.IDENTITY_NO
	 * @mbggenerated
	 */
	public void setIdentityNo(String identityNo) {
		this.identityNo = identityNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.IDENTITY_TYPE
	 * @return  the value of B2BBUSI.T_APPLICANT.IDENTITY_TYPE
	 * @mbggenerated
	 */
	public String getIdentityType() {
		return identityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.IDENTITY_TYPE
	 * @param identityType  the value for B2BBUSI.T_APPLICANT.IDENTITY_TYPE
	 * @mbggenerated
	 */
	public void setIdentityType(String identityType) {
		this.identityType = identityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.NAME
	 * @return  the value of B2BBUSI.T_APPLICANT.NAME
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.NAME
	 * @param name  the value for B2BBUSI.T_APPLICANT.NAME
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.PHONE
	 * @return  the value of B2BBUSI.T_APPLICANT.PHONE
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.PHONE
	 * @param phone  the value for B2BBUSI.T_APPLICANT.PHONE
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.POST_CODE
	 * @return  the value of B2BBUSI.T_APPLICANT.POST_CODE
	 * @mbggenerated
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.POST_CODE
	 * @param postCode  the value for B2BBUSI.T_APPLICANT.POST_CODE
	 * @mbggenerated
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.SEX
	 * @return  the value of B2BBUSI.T_APPLICANT.SEX
	 * @mbggenerated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.SEX
	 * @param sex  the value for B2BBUSI.T_APPLICANT.SEX
	 * @mbggenerated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.UNIT_TYPE
	 * @return  the value of B2BBUSI.T_APPLICANT.UNIT_TYPE
	 * @mbggenerated
	 */
	public String getUnitType() {
		return unitType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.UNIT_TYPE
	 * @param unitType  the value for B2BBUSI.T_APPLICANT.UNIT_TYPE
	 * @mbggenerated
	 */
	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.INSURED_NATURE
	 * @return  the value of B2BBUSI.T_APPLICANT.INSURED_NATURE
	 * @mbggenerated
	 */
	public String getInsuredNature() {
		return insuredNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.INSURED_NATURE
	 * @param insuredNature  the value for B2BBUSI.T_APPLICANT.INSURED_NATURE
	 * @mbggenerated
	 */
	public void setInsuredNature(String insuredNature) {
		this.insuredNature = insuredNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APP_NATION
	 * @return  the value of B2BBUSI.T_APPLICANT.APP_NATION
	 * @mbggenerated
	 */
	public String getAppNation() {
		return appNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APP_NATION
	 * @param appNation  the value for B2BBUSI.T_APPLICANT.APP_NATION
	 * @mbggenerated
	 */
	public void setAppNation(String appNation) {
		this.appNation = appNation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_COM
	 * @return  the value of B2BBUSI.T_APPLICANT.APP_IDENTIFY_COM
	 * @mbggenerated
	 */
	public String getAppIdentifyCom() {
		return appIdentifyCom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_COM
	 * @param appIdentifyCom  the value for B2BBUSI.T_APPLICANT.APP_IDENTIFY_COM
	 * @mbggenerated
	 */
	public void setAppIdentifyCom(String appIdentifyCom) {
		this.appIdentifyCom = appIdentifyCom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_START_DATE
	 * @return  the value of B2BBUSI.T_APPLICANT.APP_IDENTIFY_START_DATE
	 * @mbggenerated
	 */
	public String getAppIdentifyStartDate() {
		return appIdentifyStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_START_DATE
	 * @param appIdentifyStartDate  the value for B2BBUSI.T_APPLICANT.APP_IDENTIFY_START_DATE
	 * @mbggenerated
	 */
	public void setAppIdentifyStartDate(String appIdentifyStartDate) {
		this.appIdentifyStartDate = appIdentifyStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_END_DATE
	 * @return  the value of B2BBUSI.T_APPLICANT.APP_IDENTIFY_END_DATE
	 * @mbggenerated
	 */
	public String getAppIdentifyEndDate() {
		return appIdentifyEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APP_IDENTIFY_END_DATE
	 * @param appIdentifyEndDate  the value for B2BBUSI.T_APPLICANT.APP_IDENTIFY_END_DATE
	 * @mbggenerated
	 */
	public void setAppIdentifyEndDate(String appIdentifyEndDate) {
		this.appIdentifyEndDate = appIdentifyEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.PROVINCECODE
	 * @return  the value of B2BBUSI.T_APPLICANT.PROVINCECODE
	 * @mbggenerated
	 */
	public String getProvincecode() {
		return provincecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.PROVINCECODE
	 * @param provincecode  the value for B2BBUSI.T_APPLICANT.PROVINCECODE
	 * @mbggenerated
	 */
	public void setProvincecode(String provincecode) {
		this.provincecode = provincecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.COUNTYCODE
	 * @return  the value of B2BBUSI.T_APPLICANT.COUNTYCODE
	 * @mbggenerated
	 */
	public String getCountycode() {
		return countycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.COUNTYCODE
	 * @param countycode  the value for B2BBUSI.T_APPLICANT.COUNTYCODE
	 * @mbggenerated
	 */
	public void setCountycode(String countycode) {
		this.countycode = countycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.PREFECTURECODE
	 * @return  the value of B2BBUSI.T_APPLICANT.PREFECTURECODE
	 * @mbggenerated
	 */
	public String getPrefecturecode() {
		return prefecturecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.PREFECTURECODE
	 * @param prefecturecode  the value for B2BBUSI.T_APPLICANT.PREFECTURECODE
	 * @mbggenerated
	 */
	public void setPrefecturecode(String prefecturecode) {
		this.prefecturecode = prefecturecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.ADDEDVALUETAX_ID
	 * @return  the value of B2BBUSI.T_APPLICANT.ADDEDVALUETAX_ID
	 * @mbggenerated
	 */
	public BigDecimal getAddedvaluetaxId() {
		return addedvaluetaxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.ADDEDVALUETAX_ID
	 * @param addedvaluetaxId  the value for B2BBUSI.T_APPLICANT.ADDEDVALUETAX_ID
	 * @mbggenerated
	 */
	public void setAddedvaluetaxId(BigDecimal addedvaluetaxId) {
		this.addedvaluetaxId = addedvaluetaxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APPICFLAG
	 * @return  the value of B2BBUSI.T_APPLICANT.APPICFLAG
	 * @mbggenerated
	 */
	public String getAppicflag() {
		return appicflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APPICFLAG
	 * @param appicflag  the value for B2BBUSI.T_APPLICANT.APPICFLAG
	 * @mbggenerated
	 */
	public void setAppicflag(String appicflag) {
		this.appicflag = appicflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.IS_NEED_E_INVOICE
	 * @return  the value of B2BBUSI.T_APPLICANT.IS_NEED_E_INVOICE
	 * @mbggenerated
	 */
	public String getIsNeedEInvoice() {
		return isNeedEInvoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.IS_NEED_E_INVOICE
	 * @param isNeedEInvoice  the value for B2BBUSI.T_APPLICANT.IS_NEED_E_INVOICE
	 * @mbggenerated
	 */
	public void setIsNeedEInvoice(String isNeedEInvoice) {
		this.isNeedEInvoice = isNeedEInvoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APP_CERTIFICATE_START_DATE
	 * @return  the value of B2BBUSI.T_APPLICANT.APP_CERTIFICATE_START_DATE
	 * @mbggenerated
	 */
	public String getAppCertificateStartDate() {
		return appCertificateStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APP_CERTIFICATE_START_DATE
	 * @param appCertificateStartDate  the value for B2BBUSI.T_APPLICANT.APP_CERTIFICATE_START_DATE
	 * @mbggenerated
	 */
	public void setAppCertificateStartDate(String appCertificateStartDate) {
		this.appCertificateStartDate = appCertificateStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APP_CERTIFICATE_END_DATE
	 * @return  the value of B2BBUSI.T_APPLICANT.APP_CERTIFICATE_END_DATE
	 * @mbggenerated
	 */
	public String getAppCertificateEndDate() {
		return appCertificateEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APP_CERTIFICATE_END_DATE
	 * @param appCertificateEndDate  the value for B2BBUSI.T_APPLICANT.APP_CERTIFICATE_END_DATE
	 * @mbggenerated
	 */
	public void setAppCertificateEndDate(String appCertificateEndDate) {
		this.appCertificateEndDate = appCertificateEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APPLICANT_OCCUPATION
	 * @return  the value of B2BBUSI.T_APPLICANT.APPLICANT_OCCUPATION
	 * @mbggenerated
	 */
	public String getApplicantOccupation() {
		return applicantOccupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APPLICANT_OCCUPATION
	 * @param applicantOccupation  the value for B2BBUSI.T_APPLICANT.APPLICANT_OCCUPATION
	 * @mbggenerated
	 */
	public void setApplicantOccupation(String applicantOccupation) {
		this.applicantOccupation = applicantOccupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_NAME
	 * @return  the value of B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_NAME
	 * @mbggenerated
	 */
	public String getCustomerAgentName() {
		return customerAgentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_NAME
	 * @param customerAgentName  the value for B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_NAME
	 * @mbggenerated
	 */
	public void setCustomerAgentName(String customerAgentName) {
		this.customerAgentName = customerAgentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATETYPE
	 * @return  the value of B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATETYPE
	 * @mbggenerated
	 */
	public String getCustomerAgentCertificatetype() {
		return customerAgentCertificatetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATETYPE
	 * @param customerAgentCertificatetype  the value for B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATETYPE
	 * @mbggenerated
	 */
	public void setCustomerAgentCertificatetype(String customerAgentCertificatetype) {
		this.customerAgentCertificatetype = customerAgentCertificatetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATENUM
	 * @return  the value of B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATENUM
	 * @mbggenerated
	 */
	public String getCustomerAgentCertificatenum() {
		return customerAgentCertificatenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATENUM
	 * @param customerAgentCertificatenum  the value for B2BBUSI.T_APPLICANT.CUSTOMER_AGENT_CERTIFICATENUM
	 * @mbggenerated
	 */
	public void setCustomerAgentCertificatenum(String customerAgentCertificatenum) {
		this.customerAgentCertificatenum = customerAgentCertificatenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.PAYER_ACCOUNT_NAME
	 * @return  the value of B2BBUSI.T_APPLICANT.PAYER_ACCOUNT_NAME
	 * @mbggenerated
	 */
	public String getPayerAccountName() {
		return payerAccountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.PAYER_ACCOUNT_NAME
	 * @param payerAccountName  the value for B2BBUSI.T_APPLICANT.PAYER_ACCOUNT_NAME
	 * @mbggenerated
	 */
	public void setPayerAccountName(String payerAccountName) {
		this.payerAccountName = payerAccountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE
	 * @return  the value of B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE
	 * @mbggenerated
	 */
	public String getApplicantPayerReType() {
		return applicantPayerReType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE
	 * @param applicantPayerReType  the value for B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE
	 * @mbggenerated
	 */
	public void setApplicantPayerReType(String applicantPayerReType) {
		this.applicantPayerReType = applicantPayerReType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE_REMARK
	 * @return  the value of B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE_REMARK
	 * @mbggenerated
	 */
	public String getApplicantPayerReTypeRemark() {
		return applicantPayerReTypeRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE_REMARK
	 * @param applicantPayerReTypeRemark  the value for B2BBUSI.T_APPLICANT.APPLICANT_PAYER_RE_TYPE_REMARK
	 * @mbggenerated
	 */
	public void setApplicantPayerReTypeRemark(String applicantPayerReTypeRemark) {
		this.applicantPayerReTypeRemark = applicantPayerReTypeRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.NATIONALITY
	 * @return  the value of B2BBUSI.T_APPLICANT.NATIONALITY
	 * @mbggenerated
	 */
	public String getNationality() {
		return nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.NATIONALITY
	 * @param nationality  the value for B2BBUSI.T_APPLICANT.NATIONALITY
	 * @mbggenerated
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.UNIT_OCCUPATION_NAME
	 * @return  the value of B2BBUSI.T_APPLICANT.UNIT_OCCUPATION_NAME
	 * @mbggenerated
	 */
	public String getUnitOccupationName() {
		return unitOccupationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.UNIT_OCCUPATION_NAME
	 * @param unitOccupationName  the value for B2BBUSI.T_APPLICANT.UNIT_OCCUPATION_NAME
	 * @mbggenerated
	 */
	public void setUnitOccupationName(String unitOccupationName) {
		this.unitOccupationName = unitOccupationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.PHONE_HOLDER_NAME
	 * @return  the value of B2BBUSI.T_APPLICANT.PHONE_HOLDER_NAME
	 * @mbggenerated
	 */
	public String getPhoneHolderName() {
		return phoneHolderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.PHONE_HOLDER_NAME
	 * @param phoneHolderName  the value for B2BBUSI.T_APPLICANT.PHONE_HOLDER_NAME
	 * @mbggenerated
	 */
	public void setPhoneHolderName(String phoneHolderName) {
		this.phoneHolderName = phoneHolderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.PHONE_HOLDER_IDNO
	 * @return  the value of B2BBUSI.T_APPLICANT.PHONE_HOLDER_IDNO
	 * @mbggenerated
	 */
	public String getPhoneHolderIdno() {
		return phoneHolderIdno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.PHONE_HOLDER_IDNO
	 * @param phoneHolderIdno  the value for B2BBUSI.T_APPLICANT.PHONE_HOLDER_IDNO
	 * @mbggenerated
	 */
	public void setPhoneHolderIdno(String phoneHolderIdno) {
		this.phoneHolderIdno = phoneHolderIdno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_APPLICANT.IS_PHONE_HOLDER
	 * @return  the value of B2BBUSI.T_APPLICANT.IS_PHONE_HOLDER
	 * @mbggenerated
	 */
	public String getIsPhoneHolder() {
		return isPhoneHolder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_APPLICANT.IS_PHONE_HOLDER
	 * @param isPhoneHolder  the value for B2BBUSI.T_APPLICANT.IS_PHONE_HOLDER
	 * @mbggenerated
	 */
	public void setIsPhoneHolder(String isPhoneHolder) {
		this.isPhoneHolder = isPhoneHolder;
	}
}