package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;
import java.util.Date;

public class CarTaxTJ {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX_FLAG
	 * @mbggenerated
	 */
	private String taxFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.SUM_PAYMENT
	 * @mbggenerated
	 */
	private Double sumPayment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.BENCHMARK_TAX
	 * @mbggenerated
	 */
	private Double benchmarkTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX
	 * @mbggenerated
	 */
	private Double tax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX_OVERDUE
	 * @mbggenerated
	 */
	private Double taxOverdue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.SUR_CHARGE
	 * @mbggenerated
	 */
	private Double surCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TRUNIN_ADDRESS
	 * @mbggenerated
	 */
	private String truninAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TURN_CAR_PAID_FLAG
	 * @mbggenerated
	 */
	private String turnCarPaidFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TURN_IN_DATE
	 * @mbggenerated
	 */
	private Date turnInDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.OLD_LICESE_NO
	 * @mbggenerated
	 */
	private String oldLiceseNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.PAID_FEE_CERTIFICATE
	 * @mbggenerated
	 */
	private String paidFeeCertificate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX_COM_CODE
	 * @mbggenerated
	 */
	private String taxComCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.REFUSE_REASON
	 * @mbggenerated
	 */
	private String refuseReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_TYPE
	 * @mbggenerated
	 */
	private String taxBillType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_NO
	 * @mbggenerated
	 */
	private String taxBillNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TAX_PERIOD
	 * @mbggenerated
	 */
	private String taxPeriod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.INSURED_FLAG
	 * @mbggenerated
	 */
	private String insuredFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_TYPE
	 * @mbggenerated
	 */
	private String identifyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_NUMBER
	 * @mbggenerated
	 */
	private String identifyNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.COMPUTER_NO
	 * @mbggenerated
	 */
	private String computerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.ADDRESS
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.POST_ADDRESS
	 * @mbggenerated
	 */
	private String postAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.POST_CODE
	 * @mbggenerated
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.PHONE
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.COUNTRY_CODE
	 * @mbggenerated
	 */
	private String countryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.CONTRIBUTE_FLAG
	 * @mbggenerated
	 */
	private String contributeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.OWNER_NAME
	 * @mbggenerated
	 */
	private String ownerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.LANDTAXVEHICLE_USENATURE
	 * @mbggenerated
	 */
	private String landtaxvehicleUsenature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TJSTREET_CODE
	 * @mbggenerated
	 */
	private String tjstreetCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TJFUEL_TYPE
	 * @mbggenerated
	 */
	private String tjfuelType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.TJTAXPAYER_NUMBER
	 * @mbggenerated
	 */
	private String tjtaxpayerNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX_TJ.ORGANIZATION_NAME
	 * @mbggenerated
	 */
	private String organizationName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.ID
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.ID
	 * @param id  the value for B2BBUSI.T_CAR_TAX_TJ.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_FLAG
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX_FLAG
	 * @mbggenerated
	 */
	public String getTaxFlag() {
		return taxFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_FLAG
	 * @param taxFlag  the value for B2BBUSI.T_CAR_TAX_TJ.TAX_FLAG
	 * @mbggenerated
	 */
	public void setTaxFlag(String taxFlag) {
		this.taxFlag = taxFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.SUM_PAYMENT
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.SUM_PAYMENT
	 * @mbggenerated
	 */
	public Double getSumPayment() {
		return sumPayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.SUM_PAYMENT
	 * @param sumPayment  the value for B2BBUSI.T_CAR_TAX_TJ.SUM_PAYMENT
	 * @mbggenerated
	 */
	public void setSumPayment(Double sumPayment) {
		this.sumPayment = sumPayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.BENCHMARK_TAX
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.BENCHMARK_TAX
	 * @mbggenerated
	 */
	public Double getBenchmarkTax() {
		return benchmarkTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.BENCHMARK_TAX
	 * @param benchmarkTax  the value for B2BBUSI.T_CAR_TAX_TJ.BENCHMARK_TAX
	 * @mbggenerated
	 */
	public void setBenchmarkTax(Double benchmarkTax) {
		this.benchmarkTax = benchmarkTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX
	 * @mbggenerated
	 */
	public Double getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX
	 * @param tax  the value for B2BBUSI.T_CAR_TAX_TJ.TAX
	 * @mbggenerated
	 */
	public void setTax(Double tax) {
		this.tax = tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_OVERDUE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX_OVERDUE
	 * @mbggenerated
	 */
	public Double getTaxOverdue() {
		return taxOverdue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_OVERDUE
	 * @param taxOverdue  the value for B2BBUSI.T_CAR_TAX_TJ.TAX_OVERDUE
	 * @mbggenerated
	 */
	public void setTaxOverdue(Double taxOverdue) {
		this.taxOverdue = taxOverdue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.SUR_CHARGE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.SUR_CHARGE
	 * @mbggenerated
	 */
	public Double getSurCharge() {
		return surCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.SUR_CHARGE
	 * @param surCharge  the value for B2BBUSI.T_CAR_TAX_TJ.SUR_CHARGE
	 * @mbggenerated
	 */
	public void setSurCharge(Double surCharge) {
		this.surCharge = surCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TRUNIN_ADDRESS
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TRUNIN_ADDRESS
	 * @mbggenerated
	 */
	public String getTruninAddress() {
		return truninAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TRUNIN_ADDRESS
	 * @param truninAddress  the value for B2BBUSI.T_CAR_TAX_TJ.TRUNIN_ADDRESS
	 * @mbggenerated
	 */
	public void setTruninAddress(String truninAddress) {
		this.truninAddress = truninAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TURN_CAR_PAID_FLAG
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TURN_CAR_PAID_FLAG
	 * @mbggenerated
	 */
	public String getTurnCarPaidFlag() {
		return turnCarPaidFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TURN_CAR_PAID_FLAG
	 * @param turnCarPaidFlag  the value for B2BBUSI.T_CAR_TAX_TJ.TURN_CAR_PAID_FLAG
	 * @mbggenerated
	 */
	public void setTurnCarPaidFlag(String turnCarPaidFlag) {
		this.turnCarPaidFlag = turnCarPaidFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TURN_IN_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TURN_IN_DATE
	 * @mbggenerated
	 */
	public Date getTurnInDate() {
		return turnInDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TURN_IN_DATE
	 * @param turnInDate  the value for B2BBUSI.T_CAR_TAX_TJ.TURN_IN_DATE
	 * @mbggenerated
	 */
	public void setTurnInDate(Date turnInDate) {
		this.turnInDate = turnInDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.OLD_LICESE_NO
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.OLD_LICESE_NO
	 * @mbggenerated
	 */
	public String getOldLiceseNo() {
		return oldLiceseNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.OLD_LICESE_NO
	 * @param oldLiceseNo  the value for B2BBUSI.T_CAR_TAX_TJ.OLD_LICESE_NO
	 * @mbggenerated
	 */
	public void setOldLiceseNo(String oldLiceseNo) {
		this.oldLiceseNo = oldLiceseNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.PAID_FEE_CERTIFICATE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.PAID_FEE_CERTIFICATE
	 * @mbggenerated
	 */
	public String getPaidFeeCertificate() {
		return paidFeeCertificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.PAID_FEE_CERTIFICATE
	 * @param paidFeeCertificate  the value for B2BBUSI.T_CAR_TAX_TJ.PAID_FEE_CERTIFICATE
	 * @mbggenerated
	 */
	public void setPaidFeeCertificate(String paidFeeCertificate) {
		this.paidFeeCertificate = paidFeeCertificate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_COM_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX_COM_CODE
	 * @mbggenerated
	 */
	public String getTaxComCode() {
		return taxComCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_COM_CODE
	 * @param taxComCode  the value for B2BBUSI.T_CAR_TAX_TJ.TAX_COM_CODE
	 * @mbggenerated
	 */
	public void setTaxComCode(String taxComCode) {
		this.taxComCode = taxComCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.REFUSE_REASON
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.REFUSE_REASON
	 * @mbggenerated
	 */
	public String getRefuseReason() {
		return refuseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.REFUSE_REASON
	 * @param refuseReason  the value for B2BBUSI.T_CAR_TAX_TJ.REFUSE_REASON
	 * @mbggenerated
	 */
	public void setRefuseReason(String refuseReason) {
		this.refuseReason = refuseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_TYPE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_TYPE
	 * @mbggenerated
	 */
	public String getTaxBillType() {
		return taxBillType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_TYPE
	 * @param taxBillType  the value for B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_TYPE
	 * @mbggenerated
	 */
	public void setTaxBillType(String taxBillType) {
		this.taxBillType = taxBillType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_NO
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_NO
	 * @mbggenerated
	 */
	public String getTaxBillNo() {
		return taxBillNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_NO
	 * @param taxBillNo  the value for B2BBUSI.T_CAR_TAX_TJ.TAX_BILL_NO
	 * @mbggenerated
	 */
	public void setTaxBillNo(String taxBillNo) {
		this.taxBillNo = taxBillNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_PERIOD
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TAX_PERIOD
	 * @mbggenerated
	 */
	public String getTaxPeriod() {
		return taxPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TAX_PERIOD
	 * @param taxPeriod  the value for B2BBUSI.T_CAR_TAX_TJ.TAX_PERIOD
	 * @mbggenerated
	 */
	public void setTaxPeriod(String taxPeriod) {
		this.taxPeriod = taxPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.INSURED_FLAG
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.INSURED_FLAG
	 * @mbggenerated
	 */
	public String getInsuredFlag() {
		return insuredFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.INSURED_FLAG
	 * @param insuredFlag  the value for B2BBUSI.T_CAR_TAX_TJ.INSURED_FLAG
	 * @mbggenerated
	 */
	public void setInsuredFlag(String insuredFlag) {
		this.insuredFlag = insuredFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_TYPE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_TYPE
	 * @mbggenerated
	 */
	public String getIdentifyType() {
		return identifyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_TYPE
	 * @param identifyType  the value for B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_TYPE
	 * @mbggenerated
	 */
	public void setIdentifyType(String identifyType) {
		this.identifyType = identifyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_NUMBER
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_NUMBER
	 * @mbggenerated
	 */
	public String getIdentifyNumber() {
		return identifyNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_NUMBER
	 * @param identifyNumber  the value for B2BBUSI.T_CAR_TAX_TJ.IDENTIFY_NUMBER
	 * @mbggenerated
	 */
	public void setIdentifyNumber(String identifyNumber) {
		this.identifyNumber = identifyNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.COMPUTER_NO
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.COMPUTER_NO
	 * @mbggenerated
	 */
	public String getComputerNo() {
		return computerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.COMPUTER_NO
	 * @param computerNo  the value for B2BBUSI.T_CAR_TAX_TJ.COMPUTER_NO
	 * @mbggenerated
	 */
	public void setComputerNo(String computerNo) {
		this.computerNo = computerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.ADDRESS
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.ADDRESS
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.ADDRESS
	 * @param address  the value for B2BBUSI.T_CAR_TAX_TJ.ADDRESS
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.POST_ADDRESS
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.POST_ADDRESS
	 * @mbggenerated
	 */
	public String getPostAddress() {
		return postAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.POST_ADDRESS
	 * @param postAddress  the value for B2BBUSI.T_CAR_TAX_TJ.POST_ADDRESS
	 * @mbggenerated
	 */
	public void setPostAddress(String postAddress) {
		this.postAddress = postAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.POST_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.POST_CODE
	 * @mbggenerated
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.POST_CODE
	 * @param postCode  the value for B2BBUSI.T_CAR_TAX_TJ.POST_CODE
	 * @mbggenerated
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.PHONE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.PHONE
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.PHONE
	 * @param phone  the value for B2BBUSI.T_CAR_TAX_TJ.PHONE
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.COUNTRY_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.COUNTRY_CODE
	 * @mbggenerated
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.COUNTRY_CODE
	 * @param countryCode  the value for B2BBUSI.T_CAR_TAX_TJ.COUNTRY_CODE
	 * @mbggenerated
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.CONTRIBUTE_FLAG
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.CONTRIBUTE_FLAG
	 * @mbggenerated
	 */
	public String getContributeFlag() {
		return contributeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.CONTRIBUTE_FLAG
	 * @param contributeFlag  the value for B2BBUSI.T_CAR_TAX_TJ.CONTRIBUTE_FLAG
	 * @mbggenerated
	 */
	public void setContributeFlag(String contributeFlag) {
		this.contributeFlag = contributeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.OWNER_NAME
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.OWNER_NAME
	 * @mbggenerated
	 */
	public String getOwnerName() {
		return ownerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.OWNER_NAME
	 * @param ownerName  the value for B2BBUSI.T_CAR_TAX_TJ.OWNER_NAME
	 * @mbggenerated
	 */
	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.LANDTAXVEHICLE_USENATURE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.LANDTAXVEHICLE_USENATURE
	 * @mbggenerated
	 */
	public String getLandtaxvehicleUsenature() {
		return landtaxvehicleUsenature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.LANDTAXVEHICLE_USENATURE
	 * @param landtaxvehicleUsenature  the value for B2BBUSI.T_CAR_TAX_TJ.LANDTAXVEHICLE_USENATURE
	 * @mbggenerated
	 */
	public void setLandtaxvehicleUsenature(String landtaxvehicleUsenature) {
		this.landtaxvehicleUsenature = landtaxvehicleUsenature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TJSTREET_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TJSTREET_CODE
	 * @mbggenerated
	 */
	public String getTjstreetCode() {
		return tjstreetCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TJSTREET_CODE
	 * @param tjstreetCode  the value for B2BBUSI.T_CAR_TAX_TJ.TJSTREET_CODE
	 * @mbggenerated
	 */
	public void setTjstreetCode(String tjstreetCode) {
		this.tjstreetCode = tjstreetCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TJFUEL_TYPE
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TJFUEL_TYPE
	 * @mbggenerated
	 */
	public String getTjfuelType() {
		return tjfuelType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TJFUEL_TYPE
	 * @param tjfuelType  the value for B2BBUSI.T_CAR_TAX_TJ.TJFUEL_TYPE
	 * @mbggenerated
	 */
	public void setTjfuelType(String tjfuelType) {
		this.tjfuelType = tjfuelType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.TJTAXPAYER_NUMBER
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.TJTAXPAYER_NUMBER
	 * @mbggenerated
	 */
	public String getTjtaxpayerNumber() {
		return tjtaxpayerNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.TJTAXPAYER_NUMBER
	 * @param tjtaxpayerNumber  the value for B2BBUSI.T_CAR_TAX_TJ.TJTAXPAYER_NUMBER
	 * @mbggenerated
	 */
	public void setTjtaxpayerNumber(String tjtaxpayerNumber) {
		this.tjtaxpayerNumber = tjtaxpayerNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX_TJ.ORGANIZATION_NAME
	 * @return  the value of B2BBUSI.T_CAR_TAX_TJ.ORGANIZATION_NAME
	 * @mbggenerated
	 */
	public String getOrganizationName() {
		return organizationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX_TJ.ORGANIZATION_NAME
	 * @param organizationName  the value for B2BBUSI.T_CAR_TAX_TJ.ORGANIZATION_NAME
	 * @mbggenerated
	 */
	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}
}