package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;
import java.util.Date;

public class CarTax {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_FLAG
	 * @mbggenerated
	 */
	private String taxFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.BENCHMARK_TAX
	 * @mbggenerated
	 */
	private BigDecimal benchmarkTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX
	 * @mbggenerated
	 */
	private BigDecimal tax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_OVERDUE
	 * @mbggenerated
	 */
	private BigDecimal taxOverdue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.SUR_CHARGE
	 * @mbggenerated
	 */
	private BigDecimal surCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.SUM_PAYMENT
	 * @mbggenerated
	 */
	private BigDecimal sumPayment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO
	 * @mbggenerated
	 */
	private String taxCertificateno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.REVENUE
	 * @mbggenerated
	 */
	private String revenue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.START_TAX_DATE
	 * @mbggenerated
	 */
	private Date startTaxDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.DE_DUCTION_DOCUMENT_NUMBER
	 * @mbggenerated
	 */
	private String deDuctionDocumentNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_PAYER
	 * @mbggenerated
	 */
	private String taxPayer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_CODE
	 * @mbggenerated
	 */
	private String taxCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.END_TAX_DATE
	 * @mbggenerated
	 */
	private Date endTaxDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO2
	 * @mbggenerated
	 */
	private String taxCertificateno2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.ADJUST_RATE
	 * @mbggenerated
	 */
	private Double adjustRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.ADJUST_TAX
	 * @mbggenerated
	 */
	private Double adjustTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.FREE_CAR_KIND
	 * @mbggenerated
	 */
	private String freeCarKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_CODE
	 * @mbggenerated
	 */
	private String deductiondueCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_TYPE
	 * @mbggenerated
	 */
	private String deductiondueType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO1
	 * @mbggenerated
	 */
	private String taxCertificateno1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_DEPARTMENT
	 * @mbggenerated
	 */
	private String taxDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.LAST_BZ_END_DATE
	 * @mbggenerated
	 */
	private Date lastBzEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.LAST_TAX_DATE
	 * @mbggenerated
	 */
	private Date lastTaxDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.DECLARE_DATE
	 * @mbggenerated
	 */
	private Date declareDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAXPAYER_NAME
	 * @mbggenerated
	 */
	private String taxpayerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAXPAYER_NO
	 * @mbggenerated
	 */
	private String taxpayerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.REFUSE_REASON
	 * @mbggenerated
	 */
	private String refuseReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.PAY_TAX_FLAG
	 * @mbggenerated
	 */
	private String payTaxFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_NUMBER
	 * @mbggenerated
	 */
	private String taxDocumentNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAXPAYER_IDENTIFICATION_CODE
	 * @mbggenerated
	 */
	private String taxpayerIdentificationCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_DATE
	 * @mbggenerated
	 */
	private String taxDocumentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_CAR_TAX.TAX_PAIDAREA_CODE
	 * @mbggenerated
	 */
	private String taxPaidareaCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.ID
	 * @return  the value of B2BBUSI.T_CAR_TAX.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.ID
	 * @param id  the value for B2BBUSI.T_CAR_TAX.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_FLAG
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_FLAG
	 * @mbggenerated
	 */
	public String getTaxFlag() {
		return taxFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_FLAG
	 * @param taxFlag  the value for B2BBUSI.T_CAR_TAX.TAX_FLAG
	 * @mbggenerated
	 */
	public void setTaxFlag(String taxFlag) {
		this.taxFlag = taxFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.BENCHMARK_TAX
	 * @return  the value of B2BBUSI.T_CAR_TAX.BENCHMARK_TAX
	 * @mbggenerated
	 */
	public BigDecimal getBenchmarkTax() {
		return benchmarkTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.BENCHMARK_TAX
	 * @param benchmarkTax  the value for B2BBUSI.T_CAR_TAX.BENCHMARK_TAX
	 * @mbggenerated
	 */
	public void setBenchmarkTax(BigDecimal benchmarkTax) {
		this.benchmarkTax = benchmarkTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX
	 * @mbggenerated
	 */
	public BigDecimal getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX
	 * @param tax  the value for B2BBUSI.T_CAR_TAX.TAX
	 * @mbggenerated
	 */
	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_OVERDUE
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_OVERDUE
	 * @mbggenerated
	 */
	public BigDecimal getTaxOverdue() {
		return taxOverdue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_OVERDUE
	 * @param taxOverdue  the value for B2BBUSI.T_CAR_TAX.TAX_OVERDUE
	 * @mbggenerated
	 */
	public void setTaxOverdue(BigDecimal taxOverdue) {
		this.taxOverdue = taxOverdue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.SUR_CHARGE
	 * @return  the value of B2BBUSI.T_CAR_TAX.SUR_CHARGE
	 * @mbggenerated
	 */
	public BigDecimal getSurCharge() {
		return surCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.SUR_CHARGE
	 * @param surCharge  the value for B2BBUSI.T_CAR_TAX.SUR_CHARGE
	 * @mbggenerated
	 */
	public void setSurCharge(BigDecimal surCharge) {
		this.surCharge = surCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.SUM_PAYMENT
	 * @return  the value of B2BBUSI.T_CAR_TAX.SUM_PAYMENT
	 * @mbggenerated
	 */
	public BigDecimal getSumPayment() {
		return sumPayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.SUM_PAYMENT
	 * @param sumPayment  the value for B2BBUSI.T_CAR_TAX.SUM_PAYMENT
	 * @mbggenerated
	 */
	public void setSumPayment(BigDecimal sumPayment) {
		this.sumPayment = sumPayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO
	 * @mbggenerated
	 */
	public String getTaxCertificateno() {
		return taxCertificateno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO
	 * @param taxCertificateno  the value for B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO
	 * @mbggenerated
	 */
	public void setTaxCertificateno(String taxCertificateno) {
		this.taxCertificateno = taxCertificateno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.REVENUE
	 * @return  the value of B2BBUSI.T_CAR_TAX.REVENUE
	 * @mbggenerated
	 */
	public String getRevenue() {
		return revenue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.REVENUE
	 * @param revenue  the value for B2BBUSI.T_CAR_TAX.REVENUE
	 * @mbggenerated
	 */
	public void setRevenue(String revenue) {
		this.revenue = revenue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.START_TAX_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.START_TAX_DATE
	 * @mbggenerated
	 */
	public Date getStartTaxDate() {
		return startTaxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.START_TAX_DATE
	 * @param startTaxDate  the value for B2BBUSI.T_CAR_TAX.START_TAX_DATE
	 * @mbggenerated
	 */
	public void setStartTaxDate(Date startTaxDate) {
		this.startTaxDate = startTaxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.DE_DUCTION_DOCUMENT_NUMBER
	 * @return  the value of B2BBUSI.T_CAR_TAX.DE_DUCTION_DOCUMENT_NUMBER
	 * @mbggenerated
	 */
	public String getDeDuctionDocumentNumber() {
		return deDuctionDocumentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.DE_DUCTION_DOCUMENT_NUMBER
	 * @param deDuctionDocumentNumber  the value for B2BBUSI.T_CAR_TAX.DE_DUCTION_DOCUMENT_NUMBER
	 * @mbggenerated
	 */
	public void setDeDuctionDocumentNumber(String deDuctionDocumentNumber) {
		this.deDuctionDocumentNumber = deDuctionDocumentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_PAYER
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_PAYER
	 * @mbggenerated
	 */
	public String getTaxPayer() {
		return taxPayer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_PAYER
	 * @param taxPayer  the value for B2BBUSI.T_CAR_TAX.TAX_PAYER
	 * @mbggenerated
	 */
	public void setTaxPayer(String taxPayer) {
		this.taxPayer = taxPayer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_CODE
	 * @mbggenerated
	 */
	public String getTaxCode() {
		return taxCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_CODE
	 * @param taxCode  the value for B2BBUSI.T_CAR_TAX.TAX_CODE
	 * @mbggenerated
	 */
	public void setTaxCode(String taxCode) {
		this.taxCode = taxCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.END_TAX_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.END_TAX_DATE
	 * @mbggenerated
	 */
	public Date getEndTaxDate() {
		return endTaxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.END_TAX_DATE
	 * @param endTaxDate  the value for B2BBUSI.T_CAR_TAX.END_TAX_DATE
	 * @mbggenerated
	 */
	public void setEndTaxDate(Date endTaxDate) {
		this.endTaxDate = endTaxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO2
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO2
	 * @mbggenerated
	 */
	public String getTaxCertificateno2() {
		return taxCertificateno2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO2
	 * @param taxCertificateno2  the value for B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO2
	 * @mbggenerated
	 */
	public void setTaxCertificateno2(String taxCertificateno2) {
		this.taxCertificateno2 = taxCertificateno2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.ADJUST_RATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.ADJUST_RATE
	 * @mbggenerated
	 */
	public Double getAdjustRate() {
		return adjustRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.ADJUST_RATE
	 * @param adjustRate  the value for B2BBUSI.T_CAR_TAX.ADJUST_RATE
	 * @mbggenerated
	 */
	public void setAdjustRate(Double adjustRate) {
		this.adjustRate = adjustRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.ADJUST_TAX
	 * @return  the value of B2BBUSI.T_CAR_TAX.ADJUST_TAX
	 * @mbggenerated
	 */
	public Double getAdjustTax() {
		return adjustTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.ADJUST_TAX
	 * @param adjustTax  the value for B2BBUSI.T_CAR_TAX.ADJUST_TAX
	 * @mbggenerated
	 */
	public void setAdjustTax(Double adjustTax) {
		this.adjustTax = adjustTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.FREE_CAR_KIND
	 * @return  the value of B2BBUSI.T_CAR_TAX.FREE_CAR_KIND
	 * @mbggenerated
	 */
	public String getFreeCarKind() {
		return freeCarKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.FREE_CAR_KIND
	 * @param freeCarKind  the value for B2BBUSI.T_CAR_TAX.FREE_CAR_KIND
	 * @mbggenerated
	 */
	public void setFreeCarKind(String freeCarKind) {
		this.freeCarKind = freeCarKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_CODE
	 * @mbggenerated
	 */
	public String getDeductiondueCode() {
		return deductiondueCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_CODE
	 * @param deductiondueCode  the value for B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_CODE
	 * @mbggenerated
	 */
	public void setDeductiondueCode(String deductiondueCode) {
		this.deductiondueCode = deductiondueCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_TYPE
	 * @return  the value of B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_TYPE
	 * @mbggenerated
	 */
	public String getDeductiondueType() {
		return deductiondueType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_TYPE
	 * @param deductiondueType  the value for B2BBUSI.T_CAR_TAX.DEDUCTIONDUE_TYPE
	 * @mbggenerated
	 */
	public void setDeductiondueType(String deductiondueType) {
		this.deductiondueType = deductiondueType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO1
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO1
	 * @mbggenerated
	 */
	public String getTaxCertificateno1() {
		return taxCertificateno1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO1
	 * @param taxCertificateno1  the value for B2BBUSI.T_CAR_TAX.TAX_CERTIFICATENO1
	 * @mbggenerated
	 */
	public void setTaxCertificateno1(String taxCertificateno1) {
		this.taxCertificateno1 = taxCertificateno1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_DEPARTMENT
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_DEPARTMENT
	 * @mbggenerated
	 */
	public String getTaxDepartment() {
		return taxDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_DEPARTMENT
	 * @param taxDepartment  the value for B2BBUSI.T_CAR_TAX.TAX_DEPARTMENT
	 * @mbggenerated
	 */
	public void setTaxDepartment(String taxDepartment) {
		this.taxDepartment = taxDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.LAST_BZ_END_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.LAST_BZ_END_DATE
	 * @mbggenerated
	 */
	public Date getLastBzEndDate() {
		return lastBzEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.LAST_BZ_END_DATE
	 * @param lastBzEndDate  the value for B2BBUSI.T_CAR_TAX.LAST_BZ_END_DATE
	 * @mbggenerated
	 */
	public void setLastBzEndDate(Date lastBzEndDate) {
		this.lastBzEndDate = lastBzEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.LAST_TAX_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.LAST_TAX_DATE
	 * @mbggenerated
	 */
	public Date getLastTaxDate() {
		return lastTaxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.LAST_TAX_DATE
	 * @param lastTaxDate  the value for B2BBUSI.T_CAR_TAX.LAST_TAX_DATE
	 * @mbggenerated
	 */
	public void setLastTaxDate(Date lastTaxDate) {
		this.lastTaxDate = lastTaxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.DECLARE_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.DECLARE_DATE
	 * @mbggenerated
	 */
	public Date getDeclareDate() {
		return declareDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.DECLARE_DATE
	 * @param declareDate  the value for B2BBUSI.T_CAR_TAX.DECLARE_DATE
	 * @mbggenerated
	 */
	public void setDeclareDate(Date declareDate) {
		this.declareDate = declareDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAXPAYER_NAME
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAXPAYER_NAME
	 * @mbggenerated
	 */
	public String getTaxpayerName() {
		return taxpayerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAXPAYER_NAME
	 * @param taxpayerName  the value for B2BBUSI.T_CAR_TAX.TAXPAYER_NAME
	 * @mbggenerated
	 */
	public void setTaxpayerName(String taxpayerName) {
		this.taxpayerName = taxpayerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAXPAYER_NO
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAXPAYER_NO
	 * @mbggenerated
	 */
	public String getTaxpayerNo() {
		return taxpayerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAXPAYER_NO
	 * @param taxpayerNo  the value for B2BBUSI.T_CAR_TAX.TAXPAYER_NO
	 * @mbggenerated
	 */
	public void setTaxpayerNo(String taxpayerNo) {
		this.taxpayerNo = taxpayerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.REFUSE_REASON
	 * @return  the value of B2BBUSI.T_CAR_TAX.REFUSE_REASON
	 * @mbggenerated
	 */
	public String getRefuseReason() {
		return refuseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.REFUSE_REASON
	 * @param refuseReason  the value for B2BBUSI.T_CAR_TAX.REFUSE_REASON
	 * @mbggenerated
	 */
	public void setRefuseReason(String refuseReason) {
		this.refuseReason = refuseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.PAY_TAX_FLAG
	 * @return  the value of B2BBUSI.T_CAR_TAX.PAY_TAX_FLAG
	 * @mbggenerated
	 */
	public String getPayTaxFlag() {
		return payTaxFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.PAY_TAX_FLAG
	 * @param payTaxFlag  the value for B2BBUSI.T_CAR_TAX.PAY_TAX_FLAG
	 * @mbggenerated
	 */
	public void setPayTaxFlag(String payTaxFlag) {
		this.payTaxFlag = payTaxFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_NUMBER
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_NUMBER
	 * @mbggenerated
	 */
	public String getTaxDocumentNumber() {
		return taxDocumentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_NUMBER
	 * @param taxDocumentNumber  the value for B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_NUMBER
	 * @mbggenerated
	 */
	public void setTaxDocumentNumber(String taxDocumentNumber) {
		this.taxDocumentNumber = taxDocumentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAXPAYER_IDENTIFICATION_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAXPAYER_IDENTIFICATION_CODE
	 * @mbggenerated
	 */
	public String getTaxpayerIdentificationCode() {
		return taxpayerIdentificationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAXPAYER_IDENTIFICATION_CODE
	 * @param taxpayerIdentificationCode  the value for B2BBUSI.T_CAR_TAX.TAXPAYER_IDENTIFICATION_CODE
	 * @mbggenerated
	 */
	public void setTaxpayerIdentificationCode(String taxpayerIdentificationCode) {
		this.taxpayerIdentificationCode = taxpayerIdentificationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_DATE
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_DATE
	 * @mbggenerated
	 */
	public String getTaxDocumentDate() {
		return taxDocumentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_DATE
	 * @param taxDocumentDate  the value for B2BBUSI.T_CAR_TAX.TAX_DOCUMENT_DATE
	 * @mbggenerated
	 */
	public void setTaxDocumentDate(String taxDocumentDate) {
		this.taxDocumentDate = taxDocumentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_CAR_TAX.TAX_PAIDAREA_CODE
	 * @return  the value of B2BBUSI.T_CAR_TAX.TAX_PAIDAREA_CODE
	 * @mbggenerated
	 */
	public String getTaxPaidareaCode() {
		return taxPaidareaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_CAR_TAX.TAX_PAIDAREA_CODE
	 * @param taxPaidareaCode  the value for B2BBUSI.T_CAR_TAX.TAX_PAIDAREA_CODE
	 * @mbggenerated
	 */
	public void setTaxPaidareaCode(String taxPaidareaCode) {
		this.taxPaidareaCode = taxPaidareaCode;
	}
}