package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;
import java.util.Date;

public class InsuranceApplicationNew {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_CODE
	 * @mbggenerated
	 */
	private String btbChannelCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.AGREEMENT_NO
	 * @mbggenerated
	 */
	private String agreementNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.REL_CHANNLE_CODE
	 * @mbggenerated
	 */
	private String relChannleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUSINESS_NATURE
	 * @mbggenerated
	 */
	private String businessNature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.COM_CODE
	 * @mbggenerated
	 */
	private String comCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_CATEGORY
	 * @mbggenerated
	 */
	private String insuranceCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.APPLICATION_NO
	 * @mbggenerated
	 */
	private String applicationNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.POLICY_NO
	 * @mbggenerated
	 */
	private String policyNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.CREATE_DATE
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.EFFECT_DATE
	 * @mbggenerated
	 */
	private Date effectDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.QUIT_DATE
	 * @mbggenerated
	 */
	private Date quitDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.DESTROY_DATE
	 * @mbggenerated
	 */
	private Date destroyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.PREMIUM
	 * @mbggenerated
	 */
	private BigDecimal premium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.SUM_INSURED
	 * @mbggenerated
	 */
	private BigDecimal sumInsured;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.RISK_CODE
	 * @mbggenerated
	 */
	private String riskCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURED_E_ID
	 * @mbggenerated
	 */
	private BigDecimal insuredEId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_APPLICATION_ID
	 * @mbggenerated
	 */
	private BigDecimal insuranceApplicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_CODE
	 * @mbggenerated
	 */
	private String formulaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.MERGE_PRINT
	 * @mbggenerated
	 */
	private String mergePrint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUY_NUM
	 * @mbggenerated
	 */
	private Integer buyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_NAME
	 * @mbggenerated
	 */
	private String btbChannelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_NAME
	 * @mbggenerated
	 */
	private String formulaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.SERIAL_NUMBER
	 * @mbggenerated
	 */
	private String serialNumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.ID
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.ID
	 * @param id  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_CODE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_CODE
	 * @mbggenerated
	 */
	public String getBtbChannelCode() {
		return btbChannelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_CODE
	 * @param btbChannelCode  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_CODE
	 * @mbggenerated
	 */
	public void setBtbChannelCode(String btbChannelCode) {
		this.btbChannelCode = btbChannelCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.AGREEMENT_NO
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.AGREEMENT_NO
	 * @mbggenerated
	 */
	public String getAgreementNo() {
		return agreementNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.AGREEMENT_NO
	 * @param agreementNo  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.AGREEMENT_NO
	 * @mbggenerated
	 */
	public void setAgreementNo(String agreementNo) {
		this.agreementNo = agreementNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.REL_CHANNLE_CODE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.REL_CHANNLE_CODE
	 * @mbggenerated
	 */
	public String getRelChannleCode() {
		return relChannleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.REL_CHANNLE_CODE
	 * @param relChannleCode  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.REL_CHANNLE_CODE
	 * @mbggenerated
	 */
	public void setRelChannleCode(String relChannleCode) {
		this.relChannleCode = relChannleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUSINESS_NATURE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUSINESS_NATURE
	 * @mbggenerated
	 */
	public String getBusinessNature() {
		return businessNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUSINESS_NATURE
	 * @param businessNature  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUSINESS_NATURE
	 * @mbggenerated
	 */
	public void setBusinessNature(String businessNature) {
		this.businessNature = businessNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.COM_CODE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.COM_CODE
	 * @mbggenerated
	 */
	public String getComCode() {
		return comCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.COM_CODE
	 * @param comCode  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.COM_CODE
	 * @mbggenerated
	 */
	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_CATEGORY
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_CATEGORY
	 * @mbggenerated
	 */
	public String getInsuranceCategory() {
		return insuranceCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_CATEGORY
	 * @param insuranceCategory  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_CATEGORY
	 * @mbggenerated
	 */
	public void setInsuranceCategory(String insuranceCategory) {
		this.insuranceCategory = insuranceCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.APPLICATION_NO
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.APPLICATION_NO
	 * @mbggenerated
	 */
	public String getApplicationNo() {
		return applicationNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.APPLICATION_NO
	 * @param applicationNo  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.APPLICATION_NO
	 * @mbggenerated
	 */
	public void setApplicationNo(String applicationNo) {
		this.applicationNo = applicationNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.POLICY_NO
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.POLICY_NO
	 * @mbggenerated
	 */
	public String getPolicyNo() {
		return policyNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.POLICY_NO
	 * @param policyNo  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.POLICY_NO
	 * @mbggenerated
	 */
	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.CREATE_DATE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.CREATE_DATE
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.CREATE_DATE
	 * @param createDate  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.CREATE_DATE
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.EFFECT_DATE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.EFFECT_DATE
	 * @mbggenerated
	 */
	public Date getEffectDate() {
		return effectDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.EFFECT_DATE
	 * @param effectDate  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.EFFECT_DATE
	 * @mbggenerated
	 */
	public void setEffectDate(Date effectDate) {
		this.effectDate = effectDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.QUIT_DATE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.QUIT_DATE
	 * @mbggenerated
	 */
	public Date getQuitDate() {
		return quitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.QUIT_DATE
	 * @param quitDate  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.QUIT_DATE
	 * @mbggenerated
	 */
	public void setQuitDate(Date quitDate) {
		this.quitDate = quitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.DESTROY_DATE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.DESTROY_DATE
	 * @mbggenerated
	 */
	public Date getDestroyDate() {
		return destroyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.DESTROY_DATE
	 * @param destroyDate  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.DESTROY_DATE
	 * @mbggenerated
	 */
	public void setDestroyDate(Date destroyDate) {
		this.destroyDate = destroyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.PREMIUM
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.PREMIUM
	 * @mbggenerated
	 */
	public BigDecimal getPremium() {
		return premium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.PREMIUM
	 * @param premium  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.PREMIUM
	 * @mbggenerated
	 */
	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.SUM_INSURED
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.SUM_INSURED
	 * @mbggenerated
	 */
	public BigDecimal getSumInsured() {
		return sumInsured;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.SUM_INSURED
	 * @param sumInsured  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.SUM_INSURED
	 * @mbggenerated
	 */
	public void setSumInsured(BigDecimal sumInsured) {
		this.sumInsured = sumInsured;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.RISK_CODE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.RISK_CODE
	 * @mbggenerated
	 */
	public String getRiskCode() {
		return riskCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.RISK_CODE
	 * @param riskCode  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.RISK_CODE
	 * @mbggenerated
	 */
	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURED_E_ID
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURED_E_ID
	 * @mbggenerated
	 */
	public BigDecimal getInsuredEId() {
		return insuredEId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURED_E_ID
	 * @param insuredEId  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURED_E_ID
	 * @mbggenerated
	 */
	public void setInsuredEId(BigDecimal insuredEId) {
		this.insuredEId = insuredEId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_APPLICATION_ID
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_APPLICATION_ID
	 * @mbggenerated
	 */
	public BigDecimal getInsuranceApplicationId() {
		return insuranceApplicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_APPLICATION_ID
	 * @param insuranceApplicationId  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.INSURANCE_APPLICATION_ID
	 * @mbggenerated
	 */
	public void setInsuranceApplicationId(BigDecimal insuranceApplicationId) {
		this.insuranceApplicationId = insuranceApplicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_CODE
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_CODE
	 * @mbggenerated
	 */
	public String getFormulaCode() {
		return formulaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_CODE
	 * @param formulaCode  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_CODE
	 * @mbggenerated
	 */
	public void setFormulaCode(String formulaCode) {
		this.formulaCode = formulaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.MERGE_PRINT
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.MERGE_PRINT
	 * @mbggenerated
	 */
	public String getMergePrint() {
		return mergePrint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.MERGE_PRINT
	 * @param mergePrint  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.MERGE_PRINT
	 * @mbggenerated
	 */
	public void setMergePrint(String mergePrint) {
		this.mergePrint = mergePrint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUY_NUM
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUY_NUM
	 * @mbggenerated
	 */
	public Integer getBuyNum() {
		return buyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUY_NUM
	 * @param buyNum  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.BUY_NUM
	 * @mbggenerated
	 */
	public void setBuyNum(Integer buyNum) {
		this.buyNum = buyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_NAME
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_NAME
	 * @mbggenerated
	 */
	public String getBtbChannelName() {
		return btbChannelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_NAME
	 * @param btbChannelName  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.BTB_CHANNEL_NAME
	 * @mbggenerated
	 */
	public void setBtbChannelName(String btbChannelName) {
		this.btbChannelName = btbChannelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_NAME
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_NAME
	 * @mbggenerated
	 */
	public String getFormulaName() {
		return formulaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_NAME
	 * @param formulaName  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.FORMULA_NAME
	 * @mbggenerated
	 */
	public void setFormulaName(String formulaName) {
		this.formulaName = formulaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.SERIAL_NUMBER
	 * @return  the value of B2BBUSI.T_INSURANCE_APPLICATION_NEW.SERIAL_NUMBER
	 * @mbggenerated
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_INSURANCE_APPLICATION_NEW.SERIAL_NUMBER
	 * @param serialNumber  the value for B2BBUSI.T_INSURANCE_APPLICATION_NEW.SERIAL_NUMBER
	 * @mbggenerated
	 */
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}
}