package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;


public interface KindDAO {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_KIND
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(BigDecimal id) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_KIND
	 * @mbggenerated
	 */
	void insert(Kind record) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_KIND
	 * @mbggenerated
	 */
	void insertSelective(Kind record) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_KIND
	 * @mbggenerated
	 */
	Kind selectByPrimaryKey(BigDecimal id) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_KIND
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Kind record) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_KIND
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Kind record) throws SQLException;
	List<Kind> selectKindList(BigDecimal quotePriceInfoId) throws SQLException;	
    void deleteKindList(BigDecimal quotePriceInfoId) throws SQLException;
}