package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;

public class Kind {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ADJUST_RATE
	 * @mbggenerated
	 */
	private BigDecimal adjustRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.AMOUNT
	 * @mbggenerated
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.BENCHMARK_PREMIUM
	 * @mbggenerated
	 */
	private BigDecimal benchmarkPremium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.DEDUCTIBLE_RATE
	 * @mbggenerated
	 */
	private BigDecimal deductibleRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.DEDUCTIBLE_VALUE
	 * @mbggenerated
	 */
	private BigDecimal deductibleValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.DIS_COUNT
	 * @mbggenerated
	 */
	private BigDecimal disCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ISCOMMON
	 * @mbggenerated
	 */
	private String iscommon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.KIND_CODE
	 * @mbggenerated
	 */
	private String kindCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.KIND_FLAG
	 * @mbggenerated
	 */
	private String kindFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.KIND_NAME
	 * @mbggenerated
	 */
	private String kindName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.MODE_CODE
	 * @mbggenerated
	 */
	private String modeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.PREMIUM
	 * @mbggenerated
	 */
	private BigDecimal premium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.QUANTITY
	 * @mbggenerated
	 */
	private Long quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.RATE
	 * @mbggenerated
	 */
	private Double rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.SERIALNO
	 * @mbggenerated
	 */
	private Long serialno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.UNIT_AMOUNT
	 * @mbggenerated
	 */
	private BigDecimal unitAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.QUOTE_PRICE_INFO_ID
	 * @mbggenerated
	 */
	private BigDecimal quotePriceInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.AMOUNT_FLAG
	 * @mbggenerated
	 */
	private String amountFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.RISK_CODE
	 * @mbggenerated
	 */
	private String riskCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.RATION_TYPE
	 * @mbggenerated
	 */
	private String rationType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ITEM_CODE
	 * @mbggenerated
	 */
	private String itemCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ITEM_DETAIL_NAME
	 * @mbggenerated
	 */
	private String itemDetailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.CALCULATE_FLAG
	 * @mbggenerated
	 */
	private String calculateFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.UNIT
	 * @mbggenerated
	 */
	private Long unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.VALUE
	 * @mbggenerated
	 */
	private BigDecimal value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ACCIDENT_QUANTITY
	 * @mbggenerated
	 */
	private BigDecimal accidentQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ACCIDENT_AMOUNT
	 * @mbggenerated
	 */
	private BigDecimal accidentAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.ABSOLUTE_DEDUCTIBLE_RATE
	 * @mbggenerated
	 */
	private String absoluteDeductibleRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.DEDUCTIBLE_PREMIUM
	 * @mbggenerated
	 */
	private BigDecimal deductiblePremium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_KIND.DEDUCTIBLE_STD_PREMIUM
	 * @mbggenerated
	 */
	private BigDecimal deductibleStdPremium;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ID
	 * @return  the value of B2BBUSI.T_KIND.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ID
	 * @param id  the value for B2BBUSI.T_KIND.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ADJUST_RATE
	 * @return  the value of B2BBUSI.T_KIND.ADJUST_RATE
	 * @mbggenerated
	 */
	public BigDecimal getAdjustRate() {
		return adjustRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ADJUST_RATE
	 * @param adjustRate  the value for B2BBUSI.T_KIND.ADJUST_RATE
	 * @mbggenerated
	 */
	public void setAdjustRate(BigDecimal adjustRate) {
		this.adjustRate = adjustRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.AMOUNT
	 * @return  the value of B2BBUSI.T_KIND.AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.AMOUNT
	 * @param amount  the value for B2BBUSI.T_KIND.AMOUNT
	 * @mbggenerated
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.BENCHMARK_PREMIUM
	 * @return  the value of B2BBUSI.T_KIND.BENCHMARK_PREMIUM
	 * @mbggenerated
	 */
	public BigDecimal getBenchmarkPremium() {
		return benchmarkPremium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.BENCHMARK_PREMIUM
	 * @param benchmarkPremium  the value for B2BBUSI.T_KIND.BENCHMARK_PREMIUM
	 * @mbggenerated
	 */
	public void setBenchmarkPremium(BigDecimal benchmarkPremium) {
		this.benchmarkPremium = benchmarkPremium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_RATE
	 * @return  the value of B2BBUSI.T_KIND.DEDUCTIBLE_RATE
	 * @mbggenerated
	 */
	public BigDecimal getDeductibleRate() {
		return deductibleRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_RATE
	 * @param deductibleRate  the value for B2BBUSI.T_KIND.DEDUCTIBLE_RATE
	 * @mbggenerated
	 */
	public void setDeductibleRate(BigDecimal deductibleRate) {
		this.deductibleRate = deductibleRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_VALUE
	 * @return  the value of B2BBUSI.T_KIND.DEDUCTIBLE_VALUE
	 * @mbggenerated
	 */
	public BigDecimal getDeductibleValue() {
		return deductibleValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_VALUE
	 * @param deductibleValue  the value for B2BBUSI.T_KIND.DEDUCTIBLE_VALUE
	 * @mbggenerated
	 */
	public void setDeductibleValue(BigDecimal deductibleValue) {
		this.deductibleValue = deductibleValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.DIS_COUNT
	 * @return  the value of B2BBUSI.T_KIND.DIS_COUNT
	 * @mbggenerated
	 */
	public BigDecimal getDisCount() {
		return disCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.DIS_COUNT
	 * @param disCount  the value for B2BBUSI.T_KIND.DIS_COUNT
	 * @mbggenerated
	 */
	public void setDisCount(BigDecimal disCount) {
		this.disCount = disCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ISCOMMON
	 * @return  the value of B2BBUSI.T_KIND.ISCOMMON
	 * @mbggenerated
	 */
	public String getIscommon() {
		return iscommon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ISCOMMON
	 * @param iscommon  the value for B2BBUSI.T_KIND.ISCOMMON
	 * @mbggenerated
	 */
	public void setIscommon(String iscommon) {
		this.iscommon = iscommon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.KIND_CODE
	 * @return  the value of B2BBUSI.T_KIND.KIND_CODE
	 * @mbggenerated
	 */
	public String getKindCode() {
		return kindCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.KIND_CODE
	 * @param kindCode  the value for B2BBUSI.T_KIND.KIND_CODE
	 * @mbggenerated
	 */
	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.KIND_FLAG
	 * @return  the value of B2BBUSI.T_KIND.KIND_FLAG
	 * @mbggenerated
	 */
	public String getKindFlag() {
		return kindFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.KIND_FLAG
	 * @param kindFlag  the value for B2BBUSI.T_KIND.KIND_FLAG
	 * @mbggenerated
	 */
	public void setKindFlag(String kindFlag) {
		this.kindFlag = kindFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.KIND_NAME
	 * @return  the value of B2BBUSI.T_KIND.KIND_NAME
	 * @mbggenerated
	 */
	public String getKindName() {
		return kindName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.KIND_NAME
	 * @param kindName  the value for B2BBUSI.T_KIND.KIND_NAME
	 * @mbggenerated
	 */
	public void setKindName(String kindName) {
		this.kindName = kindName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.MODE_CODE
	 * @return  the value of B2BBUSI.T_KIND.MODE_CODE
	 * @mbggenerated
	 */
	public String getModeCode() {
		return modeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.MODE_CODE
	 * @param modeCode  the value for B2BBUSI.T_KIND.MODE_CODE
	 * @mbggenerated
	 */
	public void setModeCode(String modeCode) {
		this.modeCode = modeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.PREMIUM
	 * @return  the value of B2BBUSI.T_KIND.PREMIUM
	 * @mbggenerated
	 */
	public BigDecimal getPremium() {
		return premium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.PREMIUM
	 * @param premium  the value for B2BBUSI.T_KIND.PREMIUM
	 * @mbggenerated
	 */
	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.QUANTITY
	 * @return  the value of B2BBUSI.T_KIND.QUANTITY
	 * @mbggenerated
	 */
	public Long getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.QUANTITY
	 * @param quantity  the value for B2BBUSI.T_KIND.QUANTITY
	 * @mbggenerated
	 */
	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.RATE
	 * @return  the value of B2BBUSI.T_KIND.RATE
	 * @mbggenerated
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.RATE
	 * @param rate  the value for B2BBUSI.T_KIND.RATE
	 * @mbggenerated
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.SERIALNO
	 * @return  the value of B2BBUSI.T_KIND.SERIALNO
	 * @mbggenerated
	 */
	public Long getSerialno() {
		return serialno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.SERIALNO
	 * @param serialno  the value for B2BBUSI.T_KIND.SERIALNO
	 * @mbggenerated
	 */
	public void setSerialno(Long serialno) {
		this.serialno = serialno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.UNIT_AMOUNT
	 * @return  the value of B2BBUSI.T_KIND.UNIT_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getUnitAmount() {
		return unitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.UNIT_AMOUNT
	 * @param unitAmount  the value for B2BBUSI.T_KIND.UNIT_AMOUNT
	 * @mbggenerated
	 */
	public void setUnitAmount(BigDecimal unitAmount) {
		this.unitAmount = unitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.QUOTE_PRICE_INFO_ID
	 * @return  the value of B2BBUSI.T_KIND.QUOTE_PRICE_INFO_ID
	 * @mbggenerated
	 */
	public BigDecimal getQuotePriceInfoId() {
		return quotePriceInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.QUOTE_PRICE_INFO_ID
	 * @param quotePriceInfoId  the value for B2BBUSI.T_KIND.QUOTE_PRICE_INFO_ID
	 * @mbggenerated
	 */
	public void setQuotePriceInfoId(BigDecimal quotePriceInfoId) {
		this.quotePriceInfoId = quotePriceInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.AMOUNT_FLAG
	 * @return  the value of B2BBUSI.T_KIND.AMOUNT_FLAG
	 * @mbggenerated
	 */
	public String getAmountFlag() {
		return amountFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.AMOUNT_FLAG
	 * @param amountFlag  the value for B2BBUSI.T_KIND.AMOUNT_FLAG
	 * @mbggenerated
	 */
	public void setAmountFlag(String amountFlag) {
		this.amountFlag = amountFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.RISK_CODE
	 * @return  the value of B2BBUSI.T_KIND.RISK_CODE
	 * @mbggenerated
	 */
	public String getRiskCode() {
		return riskCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.RISK_CODE
	 * @param riskCode  the value for B2BBUSI.T_KIND.RISK_CODE
	 * @mbggenerated
	 */
	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.RATION_TYPE
	 * @return  the value of B2BBUSI.T_KIND.RATION_TYPE
	 * @mbggenerated
	 */
	public String getRationType() {
		return rationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.RATION_TYPE
	 * @param rationType  the value for B2BBUSI.T_KIND.RATION_TYPE
	 * @mbggenerated
	 */
	public void setRationType(String rationType) {
		this.rationType = rationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ITEM_CODE
	 * @return  the value of B2BBUSI.T_KIND.ITEM_CODE
	 * @mbggenerated
	 */
	public String getItemCode() {
		return itemCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ITEM_CODE
	 * @param itemCode  the value for B2BBUSI.T_KIND.ITEM_CODE
	 * @mbggenerated
	 */
	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ITEM_DETAIL_NAME
	 * @return  the value of B2BBUSI.T_KIND.ITEM_DETAIL_NAME
	 * @mbggenerated
	 */
	public String getItemDetailName() {
		return itemDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ITEM_DETAIL_NAME
	 * @param itemDetailName  the value for B2BBUSI.T_KIND.ITEM_DETAIL_NAME
	 * @mbggenerated
	 */
	public void setItemDetailName(String itemDetailName) {
		this.itemDetailName = itemDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.CALCULATE_FLAG
	 * @return  the value of B2BBUSI.T_KIND.CALCULATE_FLAG
	 * @mbggenerated
	 */
	public String getCalculateFlag() {
		return calculateFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.CALCULATE_FLAG
	 * @param calculateFlag  the value for B2BBUSI.T_KIND.CALCULATE_FLAG
	 * @mbggenerated
	 */
	public void setCalculateFlag(String calculateFlag) {
		this.calculateFlag = calculateFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.UNIT
	 * @return  the value of B2BBUSI.T_KIND.UNIT
	 * @mbggenerated
	 */
	public Long getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.UNIT
	 * @param unit  the value for B2BBUSI.T_KIND.UNIT
	 * @mbggenerated
	 */
	public void setUnit(Long unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.VALUE
	 * @return  the value of B2BBUSI.T_KIND.VALUE
	 * @mbggenerated
	 */
	public BigDecimal getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.VALUE
	 * @param value  the value for B2BBUSI.T_KIND.VALUE
	 * @mbggenerated
	 */
	public void setValue(BigDecimal value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ACCIDENT_QUANTITY
	 * @return  the value of B2BBUSI.T_KIND.ACCIDENT_QUANTITY
	 * @mbggenerated
	 */
	public BigDecimal getAccidentQuantity() {
		return accidentQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ACCIDENT_QUANTITY
	 * @param accidentQuantity  the value for B2BBUSI.T_KIND.ACCIDENT_QUANTITY
	 * @mbggenerated
	 */
	public void setAccidentQuantity(BigDecimal accidentQuantity) {
		this.accidentQuantity = accidentQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ACCIDENT_AMOUNT
	 * @return  the value of B2BBUSI.T_KIND.ACCIDENT_AMOUNT
	 * @mbggenerated
	 */
	public BigDecimal getAccidentAmount() {
		return accidentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ACCIDENT_AMOUNT
	 * @param accidentAmount  the value for B2BBUSI.T_KIND.ACCIDENT_AMOUNT
	 * @mbggenerated
	 */
	public void setAccidentAmount(BigDecimal accidentAmount) {
		this.accidentAmount = accidentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.ABSOLUTE_DEDUCTIBLE_RATE
	 * @return  the value of B2BBUSI.T_KIND.ABSOLUTE_DEDUCTIBLE_RATE
	 * @mbggenerated
	 */
	public String getAbsoluteDeductibleRate() {
		return absoluteDeductibleRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.ABSOLUTE_DEDUCTIBLE_RATE
	 * @param absoluteDeductibleRate  the value for B2BBUSI.T_KIND.ABSOLUTE_DEDUCTIBLE_RATE
	 * @mbggenerated
	 */
	public void setAbsoluteDeductibleRate(String absoluteDeductibleRate) {
		this.absoluteDeductibleRate = absoluteDeductibleRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_PREMIUM
	 * @return  the value of B2BBUSI.T_KIND.DEDUCTIBLE_PREMIUM
	 * @mbggenerated
	 */
	public BigDecimal getDeductiblePremium() {
		return deductiblePremium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_PREMIUM
	 * @param deductiblePremium  the value for B2BBUSI.T_KIND.DEDUCTIBLE_PREMIUM
	 * @mbggenerated
	 */
	public void setDeductiblePremium(BigDecimal deductiblePremium) {
		this.deductiblePremium = deductiblePremium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_STD_PREMIUM
	 * @return  the value of B2BBUSI.T_KIND.DEDUCTIBLE_STD_PREMIUM
	 * @mbggenerated
	 */
	public BigDecimal getDeductibleStdPremium() {
		return deductibleStdPremium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_KIND.DEDUCTIBLE_STD_PREMIUM
	 * @param deductibleStdPremium  the value for B2BBUSI.T_KIND.DEDUCTIBLE_STD_PREMIUM
	 * @mbggenerated
	 */
	public void setDeductibleStdPremium(BigDecimal deductibleStdPremium) {
		this.deductibleStdPremium = deductibleStdPremium;
	}
}