package com.ccic.salesapp.noncar.dto;
import java.math.BigDecimal;
import java.sql.SQLException;
import org.springframework.stereotype.Service;
import com.ccic.salesapp.noncar.dto.response.Order;

@Service
public interface OrderDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_ORDER
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_ORDER
	 * @mbggenerated
	 */
	void insert(Order record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_ORDER
	 * @mbggenerated
	 */
	void insertSelective(Order record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_ORDER
	 * @mbggenerated
	 */
	Order selectByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_ORDER
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Order record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_ORDER
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Order record) throws SQLException;
}