package com.ccic.salesapp.noncar.dto;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import com.ccic.salesapp.noncar.dto.request.PaymentNoApplyRequest;
import com.ccic.salesapp.noncar.dto.response.PaymentNoApplyResponse;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PaymentNoApply", targetNamespace = "http://service.ccic.com/payment/paymentnoapply/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaymentNoApply {

	/**
	 * 
	 * @param paymentNoApplyRequest
	 * @return returns
	 *         com.ccic.service.payment.paymentnoapply.bean.PaymentNoApplyResponse
	 */
	@WebMethod(action = "/payment/paymentNoApply")
	@WebResult(name = "PaymentNoApplyResponse", targetNamespace = "http://service.ccic.com/payment/paymentnoapply/bean", partName = "PaymentNoApplyResponse")
	public PaymentNoApplyResponse paymentNoApply(
			@WebParam(name = "PaymentNoApplyRequest", targetNamespace = "http://service.ccic.com/payment/paymentnoapply/bean", partName = "PaymentNoApplyRequest") PaymentNoApplyRequest paymentNoApplyRequest);

}
