package com.ccic.salesapp.noncar.dto;

import java.math.BigDecimal;
import java.util.Date;

public class PrpcmainRenewal {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.POLICY_NO
	 * @mbggenerated
	 */
	private String policyNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.AGENT_CODE
	 * @mbggenerated
	 */
	private String agentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_CODE
	 * @mbggenerated
	 */
	private String businCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE
	 * @mbggenerated
	 */
	private String businSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE2
	 * @mbggenerated
	 */
	private String businSource2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CAR_KIND_CODE
	 * @mbggenerated
	 */
	private String carKindCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CLAIM_TIMES
	 * @mbggenerated
	 */
	private Long claimTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.COINS_FLAG
	 * @mbggenerated
	 */
	private String coinsFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.COMCODE
	 * @mbggenerated
	 */
	private String comcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_HANDLESTATUS
	 * @mbggenerated
	 */
	private String curHandlestatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_STAFF_CODE
	 * @mbggenerated
	 */
	private String curStaffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NAME
	 * @mbggenerated
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NO
	 * @mbggenerated
	 */
	private String custNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.EXPORT_STATUS
	 * @mbggenerated
	 */
	private BigDecimal exportStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_SECCODE
	 * @mbggenerated
	 */
	private String handlerSeccode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUR_TYPE_CODE
	 * @mbggenerated
	 */
	private String insurTypeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_CODE
	 * @mbggenerated
	 */
	private String insuranceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_NAME
	 * @mbggenerated
	 */
	private String insuranceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDNAME
	 * @mbggenerated
	 */
	private String insuredname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.LICENSENO
	 * @mbggenerated
	 */
	private String licenseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PAY_START_DATE
	 * @mbggenerated
	 */
	private Date payStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PREMIUM
	 * @mbggenerated
	 */
	private BigDecimal premium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_CODE
	 * @mbggenerated
	 */
	private String projectCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_NAME
	 * @mbggenerated
	 */
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROTECT_STATUS
	 * @mbggenerated
	 */
	private String protectStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE
	 * @mbggenerated
	 */
	private Date respEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_START_DATE
	 * @mbggenerated
	 */
	private Date respStartDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.SERVICESET
	 * @mbggenerated
	 */
	private String serviceset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STAFF_CODE
	 * @mbggenerated
	 */
	private String staffCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STATUS
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMMANAGER_CODE
	 * @mbggenerated
	 */
	private String teammanagerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TRACK_STATUS
	 * @mbggenerated
	 */
	private String trackStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.UNDER_WRITE_END_DATE
	 * @mbggenerated
	 */
	private Date underWriteEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.UP_TIME
	 * @mbggenerated
	 */
	private Date upTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.USE_NATURE_CODE
	 * @mbggenerated
	 */
	private String useNatureCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OLD_POLICY_NO
	 * @mbggenerated
	 */
	private String oldPolicyNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_TEAMCODE
	 * @mbggenerated
	 */
	private String handlerTeamcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMCODE_CHANNELCODE
	 * @mbggenerated
	 */
	private String teamcodeChannelcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_NAME
	 * @mbggenerated
	 */
	private String businName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDCODE
	 * @mbggenerated
	 */
	private String insuredcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.FRAMENO
	 * @mbggenerated
	 */
	private String frameno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.SMS_SEND_DATE
	 * @mbggenerated
	 */
	private Date smsSendDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ISSMS_SEND
	 * @mbggenerated
	 */
	private String issmsSend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ISCALL
	 * @mbggenerated
	 */
	private String iscall;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CALL_CONTENT
	 * @mbggenerated
	 */
	private String callContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_ID
	 * @mbggenerated
	 */
	private String insuranceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CONTACT_DATE
	 * @mbggenerated
	 */
	private Date contactDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.NEXTCONTACT_DATE
	 * @mbggenerated
	 */
	private Date nextcontactDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_FLAG
	 * @mbggenerated
	 */
	private String renewalFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_FLAG
	 * @mbggenerated
	 */
	private String insuranceFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_REASON_TYPE
	 * @mbggenerated
	 */
	private String renewalReasonType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE_BAK
	 * @mbggenerated
	 */
	private Date respEndDateBak;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CHANNEL_NAME
	 * @mbggenerated
	 */
	private String channelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_STATUS
	 * @mbggenerated
	 */
	private String handlerStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.EFFE_FLAG
	 * @mbggenerated
	 */
	private String effeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ICNO_FLAG
	 * @mbggenerated
	 */
	private String icnoFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TONCOUNT
	 * @mbggenerated
	 */
	private BigDecimal toncount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STORE_ID
	 * @mbggenerated
	 */
	private BigDecimal storeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OTHERNATURE_FLAG
	 * @mbggenerated
	 */
	private String othernatureFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HCAR_FLAG
	 * @mbggenerated
	 */
	private String hcarFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATDATE
	 * @mbggenerated
	 */
	private Date operatdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATCODE
	 * @mbggenerated
	 */
	private String operatcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.POLICY_NO
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.POLICY_NO
	 * @mbggenerated
	 */
	public String getPolicyNo() {
		return policyNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.POLICY_NO
	 * @param policyNo  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.POLICY_NO
	 * @mbggenerated
	 */
	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.AGENT_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.AGENT_CODE
	 * @mbggenerated
	 */
	public String getAgentCode() {
		return agentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.AGENT_CODE
	 * @param agentCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.AGENT_CODE
	 * @mbggenerated
	 */
	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_CODE
	 * @mbggenerated
	 */
	public String getBusinCode() {
		return businCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_CODE
	 * @param businCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_CODE
	 * @mbggenerated
	 */
	public void setBusinCode(String businCode) {
		this.businCode = businCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE
	 * @mbggenerated
	 */
	public String getBusinSource() {
		return businSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE
	 * @param businSource  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE
	 * @mbggenerated
	 */
	public void setBusinSource(String businSource) {
		this.businSource = businSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE2
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE2
	 * @mbggenerated
	 */
	public String getBusinSource2() {
		return businSource2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE2
	 * @param businSource2  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_SOURCE2
	 * @mbggenerated
	 */
	public void setBusinSource2(String businSource2) {
		this.businSource2 = businSource2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CAR_KIND_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CAR_KIND_CODE
	 * @mbggenerated
	 */
	public String getCarKindCode() {
		return carKindCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CAR_KIND_CODE
	 * @param carKindCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CAR_KIND_CODE
	 * @mbggenerated
	 */
	public void setCarKindCode(String carKindCode) {
		this.carKindCode = carKindCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CLAIM_TIMES
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CLAIM_TIMES
	 * @mbggenerated
	 */
	public Long getClaimTimes() {
		return claimTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CLAIM_TIMES
	 * @param claimTimes  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CLAIM_TIMES
	 * @mbggenerated
	 */
	public void setClaimTimes(Long claimTimes) {
		this.claimTimes = claimTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.COINS_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.COINS_FLAG
	 * @mbggenerated
	 */
	public String getCoinsFlag() {
		return coinsFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.COINS_FLAG
	 * @param coinsFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.COINS_FLAG
	 * @mbggenerated
	 */
	public void setCoinsFlag(String coinsFlag) {
		this.coinsFlag = coinsFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.COMCODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.COMCODE
	 * @mbggenerated
	 */
	public String getComcode() {
		return comcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.COMCODE
	 * @param comcode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.COMCODE
	 * @mbggenerated
	 */
	public void setComcode(String comcode) {
		this.comcode = comcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_HANDLESTATUS
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_HANDLESTATUS
	 * @mbggenerated
	 */
	public String getCurHandlestatus() {
		return curHandlestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_HANDLESTATUS
	 * @param curHandlestatus  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_HANDLESTATUS
	 * @mbggenerated
	 */
	public void setCurHandlestatus(String curHandlestatus) {
		this.curHandlestatus = curHandlestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_STAFF_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_STAFF_CODE
	 * @mbggenerated
	 */
	public String getCurStaffCode() {
		return curStaffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_STAFF_CODE
	 * @param curStaffCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CUR_STAFF_CODE
	 * @mbggenerated
	 */
	public void setCurStaffCode(String curStaffCode) {
		this.curStaffCode = curStaffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NAME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NAME
	 * @mbggenerated
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NAME
	 * @param custName  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NAME
	 * @mbggenerated
	 */
	public void setCustName(String custName) {
		this.custName = custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NO
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NO
	 * @mbggenerated
	 */
	public String getCustNo() {
		return custNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NO
	 * @param custNo  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CUST_NO
	 * @mbggenerated
	 */
	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.EXPORT_STATUS
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.EXPORT_STATUS
	 * @mbggenerated
	 */
	public BigDecimal getExportStatus() {
		return exportStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.EXPORT_STATUS
	 * @param exportStatus  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.EXPORT_STATUS
	 * @mbggenerated
	 */
	public void setExportStatus(BigDecimal exportStatus) {
		this.exportStatus = exportStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_SECCODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_SECCODE
	 * @mbggenerated
	 */
	public String getHandlerSeccode() {
		return handlerSeccode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_SECCODE
	 * @param handlerSeccode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_SECCODE
	 * @mbggenerated
	 */
	public void setHandlerSeccode(String handlerSeccode) {
		this.handlerSeccode = handlerSeccode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUR_TYPE_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSUR_TYPE_CODE
	 * @mbggenerated
	 */
	public String getInsurTypeCode() {
		return insurTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUR_TYPE_CODE
	 * @param insurTypeCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSUR_TYPE_CODE
	 * @mbggenerated
	 */
	public void setInsurTypeCode(String insurTypeCode) {
		this.insurTypeCode = insurTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_CODE
	 * @mbggenerated
	 */
	public String getInsuranceCode() {
		return insuranceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_CODE
	 * @param insuranceCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_CODE
	 * @mbggenerated
	 */
	public void setInsuranceCode(String insuranceCode) {
		this.insuranceCode = insuranceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_NAME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_NAME
	 * @mbggenerated
	 */
	public String getInsuranceName() {
		return insuranceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_NAME
	 * @param insuranceName  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_NAME
	 * @mbggenerated
	 */
	public void setInsuranceName(String insuranceName) {
		this.insuranceName = insuranceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDNAME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDNAME
	 * @mbggenerated
	 */
	public String getInsuredname() {
		return insuredname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDNAME
	 * @param insuredname  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDNAME
	 * @mbggenerated
	 */
	public void setInsuredname(String insuredname) {
		this.insuredname = insuredname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.LICENSENO
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.LICENSENO
	 * @mbggenerated
	 */
	public String getLicenseno() {
		return licenseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.LICENSENO
	 * @param licenseno  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.LICENSENO
	 * @mbggenerated
	 */
	public void setLicenseno(String licenseno) {
		this.licenseno = licenseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PAY_START_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.PAY_START_DATE
	 * @mbggenerated
	 */
	public Date getPayStartDate() {
		return payStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PAY_START_DATE
	 * @param payStartDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.PAY_START_DATE
	 * @mbggenerated
	 */
	public void setPayStartDate(Date payStartDate) {
		this.payStartDate = payStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PREMIUM
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.PREMIUM
	 * @mbggenerated
	 */
	public BigDecimal getPremium() {
		return premium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PREMIUM
	 * @param premium  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.PREMIUM
	 * @mbggenerated
	 */
	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_CODE
	 * @mbggenerated
	 */
	public String getProjectCode() {
		return projectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_CODE
	 * @param projectCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_CODE
	 * @mbggenerated
	 */
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_NAME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_NAME
	 * @mbggenerated
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_NAME
	 * @param projectName  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.PROJECT_NAME
	 * @mbggenerated
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROTECT_STATUS
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.PROTECT_STATUS
	 * @mbggenerated
	 */
	public String getProtectStatus() {
		return protectStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.PROTECT_STATUS
	 * @param protectStatus  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.PROTECT_STATUS
	 * @mbggenerated
	 */
	public void setProtectStatus(String protectStatus) {
		this.protectStatus = protectStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE
	 * @mbggenerated
	 */
	public Date getRespEndDate() {
		return respEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE
	 * @param respEndDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE
	 * @mbggenerated
	 */
	public void setRespEndDate(Date respEndDate) {
		this.respEndDate = respEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_START_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_START_DATE
	 * @mbggenerated
	 */
	public Date getRespStartDate() {
		return respStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_START_DATE
	 * @param respStartDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_START_DATE
	 * @mbggenerated
	 */
	public void setRespStartDate(Date respStartDate) {
		this.respStartDate = respStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.SERVICESET
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.SERVICESET
	 * @mbggenerated
	 */
	public String getServiceset() {
		return serviceset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.SERVICESET
	 * @param serviceset  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.SERVICESET
	 * @mbggenerated
	 */
	public void setServiceset(String serviceset) {
		this.serviceset = serviceset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STAFF_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.STAFF_CODE
	 * @mbggenerated
	 */
	public String getStaffCode() {
		return staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STAFF_CODE
	 * @param staffCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.STAFF_CODE
	 * @mbggenerated
	 */
	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STATUS
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.STATUS
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STATUS
	 * @param status  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.STATUS
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMMANAGER_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMMANAGER_CODE
	 * @mbggenerated
	 */
	public String getTeammanagerCode() {
		return teammanagerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMMANAGER_CODE
	 * @param teammanagerCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMMANAGER_CODE
	 * @mbggenerated
	 */
	public void setTeammanagerCode(String teammanagerCode) {
		this.teammanagerCode = teammanagerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TRACK_STATUS
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.TRACK_STATUS
	 * @mbggenerated
	 */
	public String getTrackStatus() {
		return trackStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TRACK_STATUS
	 * @param trackStatus  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.TRACK_STATUS
	 * @mbggenerated
	 */
	public void setTrackStatus(String trackStatus) {
		this.trackStatus = trackStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.UNDER_WRITE_END_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.UNDER_WRITE_END_DATE
	 * @mbggenerated
	 */
	public Date getUnderWriteEndDate() {
		return underWriteEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.UNDER_WRITE_END_DATE
	 * @param underWriteEndDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.UNDER_WRITE_END_DATE
	 * @mbggenerated
	 */
	public void setUnderWriteEndDate(Date underWriteEndDate) {
		this.underWriteEndDate = underWriteEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CREATE_TIME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CREATE_TIME
	 * @param createTime  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.UP_TIME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.UP_TIME
	 * @mbggenerated
	 */
	public Date getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.UP_TIME
	 * @param upTime  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.UP_TIME
	 * @mbggenerated
	 */
	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.USE_NATURE_CODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.USE_NATURE_CODE
	 * @mbggenerated
	 */
	public String getUseNatureCode() {
		return useNatureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.USE_NATURE_CODE
	 * @param useNatureCode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.USE_NATURE_CODE
	 * @mbggenerated
	 */
	public void setUseNatureCode(String useNatureCode) {
		this.useNatureCode = useNatureCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OLD_POLICY_NO
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.OLD_POLICY_NO
	 * @mbggenerated
	 */
	public String getOldPolicyNo() {
		return oldPolicyNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OLD_POLICY_NO
	 * @param oldPolicyNo  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.OLD_POLICY_NO
	 * @mbggenerated
	 */
	public void setOldPolicyNo(String oldPolicyNo) {
		this.oldPolicyNo = oldPolicyNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_TEAMCODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_TEAMCODE
	 * @mbggenerated
	 */
	public String getHandlerTeamcode() {
		return handlerTeamcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_TEAMCODE
	 * @param handlerTeamcode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_TEAMCODE
	 * @mbggenerated
	 */
	public void setHandlerTeamcode(String handlerTeamcode) {
		this.handlerTeamcode = handlerTeamcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMCODE_CHANNELCODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMCODE_CHANNELCODE
	 * @mbggenerated
	 */
	public String getTeamcodeChannelcode() {
		return teamcodeChannelcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMCODE_CHANNELCODE
	 * @param teamcodeChannelcode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.TEAMCODE_CHANNELCODE
	 * @mbggenerated
	 */
	public void setTeamcodeChannelcode(String teamcodeChannelcode) {
		this.teamcodeChannelcode = teamcodeChannelcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_NAME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_NAME
	 * @mbggenerated
	 */
	public String getBusinName() {
		return businName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_NAME
	 * @param businName  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.BUSIN_NAME
	 * @mbggenerated
	 */
	public void setBusinName(String businName) {
		this.businName = businName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDCODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDCODE
	 * @mbggenerated
	 */
	public String getInsuredcode() {
		return insuredcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDCODE
	 * @param insuredcode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSUREDCODE
	 * @mbggenerated
	 */
	public void setInsuredcode(String insuredcode) {
		this.insuredcode = insuredcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.FRAMENO
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.FRAMENO
	 * @mbggenerated
	 */
	public String getFrameno() {
		return frameno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.FRAMENO
	 * @param frameno  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.FRAMENO
	 * @mbggenerated
	 */
	public void setFrameno(String frameno) {
		this.frameno = frameno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.SMS_SEND_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.SMS_SEND_DATE
	 * @mbggenerated
	 */
	public Date getSmsSendDate() {
		return smsSendDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.SMS_SEND_DATE
	 * @param smsSendDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.SMS_SEND_DATE
	 * @mbggenerated
	 */
	public void setSmsSendDate(Date smsSendDate) {
		this.smsSendDate = smsSendDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ISSMS_SEND
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.ISSMS_SEND
	 * @mbggenerated
	 */
	public String getIssmsSend() {
		return issmsSend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ISSMS_SEND
	 * @param issmsSend  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.ISSMS_SEND
	 * @mbggenerated
	 */
	public void setIssmsSend(String issmsSend) {
		this.issmsSend = issmsSend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ISCALL
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.ISCALL
	 * @mbggenerated
	 */
	public String getIscall() {
		return iscall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ISCALL
	 * @param iscall  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.ISCALL
	 * @mbggenerated
	 */
	public void setIscall(String iscall) {
		this.iscall = iscall;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CALL_CONTENT
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CALL_CONTENT
	 * @mbggenerated
	 */
	public String getCallContent() {
		return callContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CALL_CONTENT
	 * @param callContent  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CALL_CONTENT
	 * @mbggenerated
	 */
	public void setCallContent(String callContent) {
		this.callContent = callContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_ID
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_ID
	 * @mbggenerated
	 */
	public String getInsuranceId() {
		return insuranceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_ID
	 * @param insuranceId  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_ID
	 * @mbggenerated
	 */
	public void setInsuranceId(String insuranceId) {
		this.insuranceId = insuranceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CONTACT_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CONTACT_DATE
	 * @mbggenerated
	 */
	public Date getContactDate() {
		return contactDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CONTACT_DATE
	 * @param contactDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CONTACT_DATE
	 * @mbggenerated
	 */
	public void setContactDate(Date contactDate) {
		this.contactDate = contactDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.NEXTCONTACT_DATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.NEXTCONTACT_DATE
	 * @mbggenerated
	 */
	public Date getNextcontactDate() {
		return nextcontactDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.NEXTCONTACT_DATE
	 * @param nextcontactDate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.NEXTCONTACT_DATE
	 * @mbggenerated
	 */
	public void setNextcontactDate(Date nextcontactDate) {
		this.nextcontactDate = nextcontactDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_FLAG
	 * @mbggenerated
	 */
	public String getRenewalFlag() {
		return renewalFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_FLAG
	 * @param renewalFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_FLAG
	 * @mbggenerated
	 */
	public void setRenewalFlag(String renewalFlag) {
		this.renewalFlag = renewalFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_FLAG
	 * @mbggenerated
	 */
	public String getInsuranceFlag() {
		return insuranceFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_FLAG
	 * @param insuranceFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.INSURANCE_FLAG
	 * @mbggenerated
	 */
	public void setInsuranceFlag(String insuranceFlag) {
		this.insuranceFlag = insuranceFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_REASON_TYPE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_REASON_TYPE
	 * @mbggenerated
	 */
	public String getRenewalReasonType() {
		return renewalReasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_REASON_TYPE
	 * @param renewalReasonType  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.RENEWAL_REASON_TYPE
	 * @mbggenerated
	 */
	public void setRenewalReasonType(String renewalReasonType) {
		this.renewalReasonType = renewalReasonType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE_BAK
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE_BAK
	 * @mbggenerated
	 */
	public Date getRespEndDateBak() {
		return respEndDateBak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE_BAK
	 * @param respEndDateBak  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.RESP_END_DATE_BAK
	 * @mbggenerated
	 */
	public void setRespEndDateBak(Date respEndDateBak) {
		this.respEndDateBak = respEndDateBak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CHANNEL_NAME
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.CHANNEL_NAME
	 * @mbggenerated
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.CHANNEL_NAME
	 * @param channelName  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.CHANNEL_NAME
	 * @mbggenerated
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_STATUS
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_STATUS
	 * @mbggenerated
	 */
	public String getHandlerStatus() {
		return handlerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_STATUS
	 * @param handlerStatus  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.HANDLER_STATUS
	 * @mbggenerated
	 */
	public void setHandlerStatus(String handlerStatus) {
		this.handlerStatus = handlerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.EFFE_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.EFFE_FLAG
	 * @mbggenerated
	 */
	public String getEffeFlag() {
		return effeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.EFFE_FLAG
	 * @param effeFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.EFFE_FLAG
	 * @mbggenerated
	 */
	public void setEffeFlag(String effeFlag) {
		this.effeFlag = effeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ICNO_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.ICNO_FLAG
	 * @mbggenerated
	 */
	public String getIcnoFlag() {
		return icnoFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.ICNO_FLAG
	 * @param icnoFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.ICNO_FLAG
	 * @mbggenerated
	 */
	public void setIcnoFlag(String icnoFlag) {
		this.icnoFlag = icnoFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TONCOUNT
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.TONCOUNT
	 * @mbggenerated
	 */
	public BigDecimal getToncount() {
		return toncount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.TONCOUNT
	 * @param toncount  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.TONCOUNT
	 * @mbggenerated
	 */
	public void setToncount(BigDecimal toncount) {
		this.toncount = toncount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STORE_ID
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.STORE_ID
	 * @mbggenerated
	 */
	public BigDecimal getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.STORE_ID
	 * @param storeId  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.STORE_ID
	 * @mbggenerated
	 */
	public void setStoreId(BigDecimal storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OTHERNATURE_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.OTHERNATURE_FLAG
	 * @mbggenerated
	 */
	public String getOthernatureFlag() {
		return othernatureFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OTHERNATURE_FLAG
	 * @param othernatureFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.OTHERNATURE_FLAG
	 * @mbggenerated
	 */
	public void setOthernatureFlag(String othernatureFlag) {
		this.othernatureFlag = othernatureFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HCAR_FLAG
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.HCAR_FLAG
	 * @mbggenerated
	 */
	public String getHcarFlag() {
		return hcarFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.HCAR_FLAG
	 * @param hcarFlag  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.HCAR_FLAG
	 * @mbggenerated
	 */
	public void setHcarFlag(String hcarFlag) {
		this.hcarFlag = hcarFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATDATE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATDATE
	 * @mbggenerated
	 */
	public Date getOperatdate() {
		return operatdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATDATE
	 * @param operatdate  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATDATE
	 * @mbggenerated
	 */
	public void setOperatdate(Date operatdate) {
		this.operatdate = operatdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATCODE
	 * @return  the value of B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATCODE
	 * @mbggenerated
	 */
	public String getOperatcode() {
		return operatcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATCODE
	 * @param operatcode  the value for B2BBUSI.T_PRPCMAIN_RENEWAL.OPERATCODE
	 * @mbggenerated
	 */
	public void setOperatcode(String operatcode) {
		this.operatcode = operatcode;
	}
}