package com.ccic.salesapp.noncar.outService.esb.imgprevupload.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ccic.salesapp.noncar.dto.request.ImgPrevUploadRequest;
import com.ccic.salesapp.noncar.outService.esb.imgprevupload.bean.ImgPrevUploadResponse;
import com.ccic.salesapp.noncar.outService.esb.imgprevupload.bean.ObjectFactory;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-02-05T14:33:11.388+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/h5img/imgPrevUpload/intf", name = "ImgPrevUploadPort")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ImgPrevUploadPort {

    @WebResult(name = "ImgPrevUploadResponse", targetNamespace = "http://service.ccic.com/h5img/imgPrevUpload/bean", partName = "ImgPrevUploadResponse")
    @WebMethod(operationName = "ImgPrevUpload", action = "/h5img/imgPrevUpload")
    public ImgPrevUploadResponse imgPrevUpload(
        @WebParam(partName = "ImgPrevUploadRequest", name = "ImgPrevUploadRequest", targetNamespace = "http://service.ccic.com/h5img/imgPrevUpload/bean")
        ImgPrevUploadRequest imgPrevUploadRequest
    );
}
