package com.ccic.salesapp.noncar.outService.esb.imgprevupload.intf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-02-05T14:33:11.469+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "ImgPrevUploadService", 
                  wsdlLocation = "http://10.1.13.54:15006/ImgPrevUploadService?wsdl",
                  targetNamespace = "http://service.ccic.com/h5img/imgPrevUpload/intf") 
public class ImgPrevUploadService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/h5img/imgPrevUpload/intf", "ImgPrevUploadService");
    public final static QName ImgPrevUploadEndpoint = new QName("http://service.ccic.com/h5img/imgPrevUpload/intf", "ImgPrevUploadEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://10.1.13.54:15006/ImgPrevUploadService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImgPrevUploadService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.1.13.54:15006/ImgPrevUploadService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImgPrevUploadService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImgPrevUploadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImgPrevUploadService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ImgPrevUploadPort
     */
    @WebEndpoint(name = "ImgPrevUploadEndpoint")
    public ImgPrevUploadPort getImgPrevUploadEndpoint() {
        return super.getPort(ImgPrevUploadEndpoint, ImgPrevUploadPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImgPrevUploadPort
     */
    @WebEndpoint(name = "ImgPrevUploadEndpoint")
    public ImgPrevUploadPort getImgPrevUploadEndpoint(WebServiceFeature... features) {
        return super.getPort(ImgPrevUploadEndpoint, ImgPrevUploadPort.class, features);
    }

}
