package com.ccic.salesapp.noncar.outService.esb.InvoiceLink.intf;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ccic.salesapp.noncar.outService.esb.InvoiceLink.bean.InvoiceLinkQueryRequest;
import com.ccic.salesapp.noncar.outService.esb.InvoiceLink.bean.InvoiceLinkQueryResponse;
import com.ccic.salesapp.noncar.outService.esb.InvoiceLink.bean.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InvoiceLinkQueryPort", targetNamespace = "http://service.ccic.com/payment/InvoiceLinkQuery/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InvoiceLinkQueryPort {


    /**
     * 
     * @param invoiceLinkQueryRequest
     * @return
     *     returns wp.salesapp.ws.InvoiceLinkQueryResponse
     */
    @WebMethod(operationName = "InvoiceLinkQuery", action = "/services/QueryInvoiceAddress")
    @WebResult(name = "InvoiceLinkQueryResponse", targetNamespace = "http://service.ccic.com/payment/InvoiceLinkQuery/bean", partName = "InvoiceLinkQueryResponse")
    public InvoiceLinkQueryResponse invoiceLinkQuery(
        @WebParam(name = "InvoiceLinkQueryRequest", targetNamespace = "http://service.ccic.com/payment/InvoiceLinkQuery/bean", partName = "InvoiceLinkQueryRequest")
        InvoiceLinkQueryRequest invoiceLinkQueryRequest);

}
