package com.ccic.salesapp.noncar.repository.basedb.mapper;
import java.math.BigDecimal;
import java.sql.SQLException;

import org.apache.ibatis.annotations.Mapper;

import com.ccic.salesapp.noncar.dto.CarTaxTJ;

@Mapper
public interface CarTaxTJDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX_TJ
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX_TJ
	 * @mbggenerated
	 */
	void insert(CarTaxTJ record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX_TJ
	 * @mbggenerated
	 */
	void insertSelective(CarTaxTJ record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX_TJ
	 * @mbggenerated
	 */
	CarTaxTJ selectByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX_TJ
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CarTaxTJ record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX_TJ
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CarTaxTJ record) throws SQLException;
}