package com.ccic.salesapp.noncar.repository.basedb.mapper;
import java.math.BigDecimal;
import java.sql.SQLException;

import org.apache.ibatis.annotations.Mapper;

import com.ccic.salesapp.noncar.dto.CarTax;

@Mapper
public interface CarTaxDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX
	 * @mbggenerated
	 */
	void insert(CarTax record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX
	 * @mbggenerated
	 */
	void insertSelective(CarTax record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX
	 * @mbggenerated
	 */
	CarTax selectByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CarTax record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_CAR_TAX
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CarTax record) throws SQLException;
}