package com.ccic.salesapp.noncar.repository.basedb.mapper;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Mapper;
import com.ccic.salesapp.noncar.dto.InsuranceApplication;
import com.ccic.salesapp.noncar.dto.OrderListEntity;
import com.ccic.salesapp.noncar.dto.request.CustCoreInfoQuoteRequestVO;

@Mapper
public interface InsuranceApplicationDAO {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION
	 * @mbggenerated
	 */
	void insert(InsuranceApplication record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION
	 * @mbggenerated
	 */
	void insertSelective(InsuranceApplication record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION
	 * @mbggenerated
	 */
	InsuranceApplication selectByPrimaryKey(BigDecimal id) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(InsuranceApplication record) throws SQLException;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION
	 * @mbggenerated
	 */
	int updateByPrimaryKey(InsuranceApplication record) throws SQLException;

	/**
	 * 订单列表
	 */
	List<OrderListEntity> selectByOrderListQueryList(OrderListEntity orderListReq) throws SQLException;

	/**
	 * 订单详情
	 */
	InsuranceApplication selectOrderDetailsInquiry(Map paramMap) throws SQLException;
	List<InsuranceApplication> selectByProposalNo(String proposalNo) throws SQLException;

	int updateInsuranceApplicationStatus(InsuranceApplication insuranceApplication) throws SQLException;

	BigDecimal pendingEffectFeeQuery(String agentCode,String handlerCode) throws SQLException;

	//List<PlanFeeDetailVO> planFeeDetailInquiry(String agentCode,String handlerCode) throws SQLException;

	//CollectIDCardEntity selectIDCardInquiry(CollectIDCardEntity orderListReq) throws SQLException;

	int  updateInsuranceMachineCodeStatus(Map<String, String> param) throws SQLException;

	void updateHuataiPaymentStatus(Map<String, String> param) throws SQLException;

	CustCoreInfoQuoteRequestVO selectByInsuranceInquiryByOrderNo(HashMap<String, String> hashMap) throws SQLException;

	public int deleteOrderById(Map<String,Object> map) throws SQLException;

	void updateByPrimaryKey(com.ccic.salesapp.noncar.dto.response.InsuranceApplication ia);






}