package com.ccic.salesapp.noncar.outService.esb.EInvoiceApplication.intf;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ccic.salesapp.noncar.outService.esb.EInvoiceApplication.bean.EInvoiceApplicationForAppRequest;
import com.ccic.salesapp.noncar.outService.esb.EInvoiceApplication.bean.EInvoiceApplicationForAppResponse;
import com.ccic.salesapp.noncar.outService.esb.EInvoiceApplication.bean.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EinvoiceApplicationForApp", targetNamespace = "http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EinvoiceApplicationForApp {


    /**
     * 
     * @param eInvoiceApplicationForAppRequest
     * @return
     *     returns com.salesapp.ws.EInvoiceApplicationForAppResponse
     */
    @WebMethod(action = "einvoiceApplicationForApp")
    @WebResult(name = "EInvoiceApplicationForAppResponse", targetNamespace = "http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/bean", partName = "EInvoiceApplicationForAppResponse")
    public EInvoiceApplicationForAppResponse einvoiceApplicationForApp(
        @WebParam(name = "EInvoiceApplicationForAppRequest", targetNamespace = "http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/bean", partName = "EInvoiceApplicationForAppRequest")
        EInvoiceApplicationForAppRequest eInvoiceApplicationForAppRequest);

}
