package com.ccic.salesapp.noncar.outService.esb.EInvoiceApplication.intf;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EinvoiceApplicationForAppService", targetNamespace = "http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/intf", wsdlLocation = "file:/C:/Users/lenovo/EinvoiceApplicationForAppService.wsdl")
public class EinvoiceApplicationForAppService
    extends Service
{

    private final static URL EINVOICEAPPLICATIONFORAPPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EINVOICEAPPLICATIONFORAPPSERVICE_EXCEPTION;
    private final static QName EINVOICEAPPLICATIONFORAPPSERVICE_QNAME = new QName("http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/intf", "EinvoiceApplicationForAppService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/lenovo/EinvoiceApplicationForAppService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EINVOICEAPPLICATIONFORAPPSERVICE_WSDL_LOCATION = url;
        EINVOICEAPPLICATIONFORAPPSERVICE_EXCEPTION = e;
    }

    public EinvoiceApplicationForAppService() {
        super(__getWsdlLocation(), EINVOICEAPPLICATIONFORAPPSERVICE_QNAME);
    }

    public EinvoiceApplicationForAppService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EINVOICEAPPLICATIONFORAPPSERVICE_QNAME, features);
    }

    public EinvoiceApplicationForAppService(URL wsdlLocation) {
        super(wsdlLocation, EINVOICEAPPLICATIONFORAPPSERVICE_QNAME);
    }

    public EinvoiceApplicationForAppService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EINVOICEAPPLICATIONFORAPPSERVICE_QNAME, features);
    }

    public EinvoiceApplicationForAppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EinvoiceApplicationForAppService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EinvoiceApplicationForApp
     */
    @WebEndpoint(name = "EinvoiceApplicationForApp")
    public EinvoiceApplicationForApp getEinvoiceApplicationForApp() {
        return super.getPort(new QName("http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/intf", "EinvoiceApplicationForApp"), EinvoiceApplicationForApp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EinvoiceApplicationForApp
     */
    @WebEndpoint(name = "EinvoiceApplicationForApp")
    public EinvoiceApplicationForApp getEinvoiceApplicationForApp(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/einvoiceapp/einvoiceApplicationForApp/intf", "EinvoiceApplicationForApp"), EinvoiceApplicationForApp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EINVOICEAPPLICATIONFORAPPSERVICE_EXCEPTION!= null) {
            throw EINVOICEAPPLICATIONFORAPPSERVICE_EXCEPTION;
        }
        return EINVOICEAPPLICATIONFORAPPSERVICE_WSDL_LOCATION;
    }

}
