
package com.ccic.salesapp.performance.outService.esb.Withdrawals;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WithdrawalsService", targetNamespace = "http://service.ccic.com/agent/withdrawals/intf", wsdlLocation = "file:/D:/vpn/tx.wsdl")
public class WithdrawalsService
    extends Service
{

    private final static URL WITHDRAWALSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WITHDRAWALSSERVICE_EXCEPTION;
    private final static QName WITHDRAWALSSERVICE_QNAME = new QName("http://service.ccic.com/agent/withdrawals/intf", "WithdrawalsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/vpn/tx.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WITHDRAWALSSERVICE_WSDL_LOCATION = url;
        WITHDRAWALSSERVICE_EXCEPTION = e;
    }

    public WithdrawalsService() {
        super(__getWsdlLocation(), WITHDRAWALSSERVICE_QNAME);
    }

    public WithdrawalsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WITHDRAWALSSERVICE_QNAME, features);
    }

    public WithdrawalsService(URL wsdlLocation) {
        super(wsdlLocation, WITHDRAWALSSERVICE_QNAME);
    }

    public WithdrawalsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WITHDRAWALSSERVICE_QNAME, features);
    }

    public WithdrawalsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WithdrawalsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WithdrawalsPort
     */
    @WebEndpoint(name = "WithdrawalsPort")
    public WithdrawalsPort getWithdrawalsPort() {
        return super.getPort(new QName("http://service.ccic.com/agent/withdrawals/intf", "WithdrawalsPort"), WithdrawalsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WithdrawalsPort
     */
    @WebEndpoint(name = "WithdrawalsPort")
    public WithdrawalsPort getWithdrawalsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ccic.com/agent/withdrawals/intf", "WithdrawalsPort"), WithdrawalsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WITHDRAWALSSERVICE_EXCEPTION!= null) {
            throw WITHDRAWALSSERVICE_EXCEPTION;
        }
        return WITHDRAWALSSERVICE_WSDL_LOCATION;
    }

}
