
package com.ccic.salesapp.performance.outService.esb.Withdrawals;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WithdrawalsPort", targetNamespace = "http://service.ccic.com/agent/withdrawals/intf")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WithdrawalsPort {


    /**
     * 
     * @param withdrawalsRequest
     * @return
     *     returns com.esb.WithdrawalsResponse
     */
    @WebMethod(operationName = "Withdrawals", action = "/withdrawals/withdrawalsCommission")
    @WebResult(name = "WithdrawalsResponse", targetNamespace = "http://service.ccic.com/agent/withdrawals/bean", partName = "WithdrawalsResponse")
    public WithdrawalsResponse withdrawals(
        @WebParam(name = "WithdrawalsRequest", targetNamespace = "http://service.ccic.com/agent/withdrawals/bean", partName = "WithdrawalsRequest")
        WithdrawalsRequest withdrawalsRequest);

}
