package com.ccic.salesapp.noncar.outService.esb.balancequery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-12-13T15:36:01.166+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "BalanceQueryService", 
                  wsdlLocation = "file:/E:/CXF/BalanceQueryService.wsdl",
                  targetNamespace = "http://service.ccic.com/pss/balanceQuery/intf") 
public class BalanceQueryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ccic.com/pss/balanceQuery/intf", "BalanceQueryService");
    public final static QName BalanceQueryEndpoint = new QName("http://service.ccic.com/pss/balanceQuery/intf", "BalanceQueryEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/CXF/BalanceQueryService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BalanceQueryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/CXF/BalanceQueryService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BalanceQueryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BalanceQueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BalanceQueryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BalanceQueryPort
     */
    @WebEndpoint(name = "BalanceQueryEndpoint")
    public BalanceQueryPort getBalanceQueryEndpoint() {
        return super.getPort(BalanceQueryEndpoint, BalanceQueryPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BalanceQueryPort
     */
    @WebEndpoint(name = "BalanceQueryEndpoint")
    public BalanceQueryPort getBalanceQueryEndpoint(WebServiceFeature... features) {
        return super.getPort(BalanceQueryEndpoint, BalanceQueryPort.class, features);
    }

}
