package com.ccic.salesapp.noncar.outService.esb.balancequery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-12-13T15:36:01.087+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.ccic.com/pss/balanceQuery/intf", name = "BalanceQueryPort")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BalanceQueryPort {

    @WebResult(name = "BalanceQueryResponse", targetNamespace = "http://service.ccic.com/pss/balanceQuery/bean", partName = "BalanceQueryResponse")
    @WebMethod(action = "/pss/balanceQuery")
    public BalanceQueryResponse balanceQuery(
        @WebParam(partName = "BalanceQueryRequest", name = "BalanceQueryRequest", targetNamespace = "http://service.ccic.com/pss/balanceQuery/bean")
        BalanceQueryRequest balanceQueryRequest
    );
}
