package com.ccic.salesapp.noncar.repository.databusdb.po;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.ccic.salesapp.noncar.dto.InsuranceApplicationNew;


@Mapper
public interface InsuranceApplicationNewDAO {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION_NEW
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(BigDecimal id) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION_NEW
	 * @mbggenerated
	 */
	void insert(InsuranceApplicationNew record) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION_NEW
	 * @mbggenerated
	 */
	void insertSelective(InsuranceApplicationNew record) throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION_NEW
	 * @mbggenerated
	 */
	InsuranceApplicationNew selectByPrimaryKey(BigDecimal id)
			throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION_NEW
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(InsuranceApplicationNew record)
			throws SQLException;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table B2BBUSI.T_INSURANCE_APPLICATION_NEW
	 * @mbggenerated
	 */
	int updateByPrimaryKey(InsuranceApplicationNew record) throws SQLException;
	List<InsuranceApplicationNew> selectByInsuranceApplicationNewID(BigDecimal id) throws SQLException;
    void deleteByInsuranceApplicationID(BigDecimal insuranceAppID) throws SQLException;
}