
package com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.bean.PerBaseInfoInquiryRequest;
import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.bean.PerBaseInfoInquiryResponse;
import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.intf.PerBaseInfoInquiry;
import com.ccic.salesapp.noncar.outService.esb.perBaseInfoInquiry.intf.PerBaseInfoInquiryService;

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-02-27T16:59:11.664+08:00
 * Generated source version: 3.2.12
 *
 */
public final class PerBaseInfoInquiry_PerBaseInfoInquiryEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ccic.com/ecif/perbaseinfoinquiry/intf", "PerBaseInfoInquiryService");

    private PerBaseInfoInquiry_PerBaseInfoInquiryEndpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PerBaseInfoInquiryService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PerBaseInfoInquiryService ss = new PerBaseInfoInquiryService(wsdlURL, SERVICE_NAME);
        PerBaseInfoInquiry port = ss.getPerBaseInfoInquiryEndpoint();

        {
        System.out.println("Invoking process...");
        PerBaseInfoInquiryRequest _process_perBaseInfoInquiryRequest = null;
        PerBaseInfoInquiryResponse _process__return = port.process(_process_perBaseInfoInquiryRequest);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
